In [1]:
import pandas as pd
import numpy as np
import re
import requests
from bs4 import BeautifulSoup
from tqdm import tqdm
from urllib.parse import quote_plus

/disk1/anaconda3/envs/kcat/lib/python3.10/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(

In [2]:
df = pd.read_csv('data/sabiork_dataset.csv')
df.head()

,Enzyme Variant,ECNumber,UniProtKB_AC,Organism,Temperature,pH,parameter.name,parameter.type,parameter.associatedSpecies,parameter.startValue,parameter.endValue,parameter.standardDeviation,parameter.unit,Substrate
0,mutant MDH G81S,1.1.99.31,P20932,Pseudomonas putida,20.0,7.5,S,concentration,(S)-Mandelate,NaN,NaN,-,-,Riboflavin-5-phosphate;(S)-Mandelate
1,mutant MDH G81S,1.1.99.31,P20932,Pseudomonas putida,20.0,7.5,kcat,kcat,NaN,2.80000,NaN,1E-1,s^(-1),Riboflavin-5-phosphate;(S)-Mandelate
2,mutant MDH G81S,1.1.99.31,P20932,Pseudomonas putida,20.0,7.5,Km,Km,(S)-Mandelate,0.00230,NaN,2E-4,M,Riboflavin-5-phosphate;(S)-Mandelate
3,mutant MDH G81V,1.1.99.31,P20932,Pseudomonas putida,20.0,7.5,Km,Km,(S)-Mandelate,0.00017,NaN,6E-5,M,Riboflavin-5-phosphate;(S)-Mandelate
4,mutant MDH G81V,1.1.99.31,P20932,Pseudomonas putida,20.0,7.5,S,concentration,(S)-Mandelate,NaN,NaN,-,-,Riboflavin-5-phosphate;(S)-Mandelate

In [ ]:
df = df.rename(columns={'ECNumber': 'ec_number', 'Substrate': 'substrate', 'UniProtKB_AC': 'uniprot',
                        'Organism': 'organism', 'Temperature': 'temperature'})

In [4]:
df.columns

Index(['Enzyme Variant', 'ec_number', 'uniprot', 'organism', 'temperature',
       'pH', 'parameter.name', 'parameter.type', 'parameter.associatedSpecies',
       'parameter.startValue', 'parameter.endValue',
       'parameter.standardDeviation', 'parameter.unit', 'substrate'],
      dtype='object')

In [5]:
df['parameter.type'].unique()

array(['concentration', 'kcat', 'Km', 'kcat/Km', 'Vmax',
       'Hill coefficient', 'S_half', 'specific enz. activity', 'Ki',
       'pKa', 'pH', 'Kd', 'rate const.', 'unknown', 'Hill constant',
       'Keq', 'Vmax/Km', 'IC50', 'kinact', 'EC50', 'Activation constant',
       'specific concentration', 'time', 'kcat/S_half', 'half-life',
       'enthalpy change'], dtype=object)

In [ ]:
df = df[df['parameter.type'] == 'kcat']

print(f"After filtering: {len(df)}")

필터링 후 데이터 개수: 23521

In [ ]:
df = df.dropna(subset=['pH', 'temperature'])
print(f"After filtering: {len(df)}")

필터링 후 데이터 개수: 23521

## Extract sequence with Uniprot ID

In [ ]:
df = df[~df['uniprot'].str.contains(';', na=False)]
print('Data with one Uniprot ID: ', len(df))

Uniprot 값이 한 개만 있는 데이터:  22500

In [9]:
uniprot_ids = list(df['uniprot'].unique())
len(uniprot_ids)

2418

In [ ]:
def get_protein_sequence(uniprot_id: str):
    base_url = "https://rest.uniprot.org/uniprotkb/"
    url = f"{base_url}{uniprot_id}.fasta"
    
    try:
        response = requests.get(url)
        response.raise_for_status()  # Raise exception for HTTP errors
        
        # Parse the FASTA format
        lines = response.text.split('\n')
        if len(lines) > 1:
            # Join all lines except the first one (header)
            sequence = ''.join(lines[1:])
            return sequence
        return None
        
    except requests.exceptions.RequestException as e:
        print(f"Error fetching sequence for {uniprot_id}: {e}")
        return None

In [9]:
sequences = []

for id in tqdm(uniprot_ids):
    try:
        seq = get_protein_sequence(id)
        sequences.append(seq)
    except:
        sequences.append(None)

uniprot_db = pd.DataFrame({'uniprot': uniprot_ids, 'sequence': sequences})
uniprot_db.to_csv('data/sabiork_uniprot_db.csv', index=False)

  0%|          | 0/2418 [00:00<?, ?it/s]

  0%|          | 7/2418 [00:07<43:34,  1.08s/it]

Error fetching sequence for nan: 400 Client Error: Bad Request for url: https://rest.uniprot.org/uniprotkb/nan.fasta

100%|██████████| 2418/2418 [44:25<00:00,  1.10s/it]

In [8]:
uniprot_db = pd.read_csv('data/sabiork_uniprot_db.csv')

In [9]:
df = df.merge(uniprot_db[['uniprot', 'sequence']], on='uniprot', how='left')

In [ ]:
df = df.dropna(subset=['sequence'])
print(f"After removing data with no sequence information: {len(df)}")

Sequence가 없는 데이터 제거 후 데이터 개수: 21286

## Add wildtype/mutant information

In [ ]:
def extract_type_and_mutation(comment):
    if pd.isna(comment):
        return None, None
    
    is_wildtype = any(word in comment.lower() for word in ['wildtype', 'wild-type', 'wild type'])
    is_mutant = 'mutant' in comment.lower()
    
    mutations = re.findall(r'([A-Z]\d+[A-Z])', comment)
    
    if is_wildtype:
        return 'wildtype', None
    elif is_mutant:
        if mutations:
            return 'mutant', '/'.join(mutations)
        else:
            return 'mutant', None
    else:
        return None, None

df['type'] = None
df['mutation'] = None

for idx, row in df.iterrows():
    type_val, mutation_val = extract_type_and_mutation(row['Enzyme Variant'])
    df.at[idx, 'type'] = type_val
    df.at[idx, 'mutation'] = mutation_val

In [ ]:
no_type_info = df[df['type'].isna()]
print(f"Data with no type information: {len(no_type_info)}")

df = df[~((df['type'] == 'mutant') & (df['mutation'].isna()))]

print("\nTotal data length: ", len(df))
print(f"Wildtype data length: {len(df[df['type'] == 'wildtype'])}")
print(f"Mutant data length: {len(df[df['type'] == 'mutant'])}")

타입 정보가 없는 데이터 수: 0

총 데이터 수:  20275
Wildtype 데이터 수: 11783
Mutant 데이터 수: 8492

## Preprocess turnover number

In [13]:
df['turnover_number'] = df['parameter.startValue']

In [14]:
df['parameter.unit'].unique()

array(['s^(-1)', 'M^(-1)*s^(-1)', '-', 'M', 'mol*s^(-1)*mol^(-1)',
       'katal', 'J/mol', 'mol*s^(-1)*g^(-1)'], dtype=object)

In [15]:
df['parameter.name'].unique()

array(['kcat', 'k_cat', 'kcat_max', 'Kcat', 'kmax', 'kcat_2', 'kcat_1',
       'kcat_c', 'kcat_b', 'kcat_a', 'kcat0', 'kcat_B', 'kcat2', 'kcat1',
       'Kcat0', 'kcatA', 'kcatB', 'kcatR', 'kcatF', 'kcatE', 'kcat_E',
       'kcat_R', 'kcat_A', 'k0', 'V/Et', 'kc', 'k1', 'k2', 'kcatG',
       'kcat_0', 'kcat_C', 'kcat_D', 'kcat_r', 'kcat_f', 'kobs', 'v_dec',
       'kcat_act', 'kact', 'kcat_app', 'Vf_ET', 'Kcat1', 'Kcat2'],
      dtype=object)

In [ ]:
valid_kcat_units = {
    's^(-1)': 's^(-1)',
    '1/s': 's^(-1)',
    'mol*s^(-1)*mol^(-1)': 's^(-1)',  # mol/mol/s → s⁻¹
}

df = df[df['parameter.unit'].isin(valid_kcat_units)]

df['parameter.unit'] = df['parameter.unit'].map(valid_kcat_units)

In [ ]:
df = df.dropna(subset=['turnover_number'])
print('After preprocessing turnover number data: ', len(df))

Turnover number 데이터 정제 후 데이터 개수:  20241

In [18]:
df.isna().sum()

Enzyme Variant                     0
ec_number                          0
uniprot                            0
organism                           0
temperature                        0
pH                                 0
parameter.name                     0
parameter.type                     0
parameter.associatedSpecies    20241
parameter.startValue               0
parameter.endValue             20161
parameter.standardDeviation        0
parameter.unit                     0
substrate                          0
sequence                           0
type                               0
mutation                       11768
turnover_number                    0
dtype: int64

In [ ]:
sabio_substrates = ''
for i in range(len(df)):
    sabio_substrates += df.iloc[i]['substrate'] + ';'

sabio_substrates = list(set(sabio_substrates.split(';')))
print(len(sabio_substrates))

2861

In [21]:
missing_in_substrates = set(sabio_substrates) - set(substrates['substrate'])
missing_in_substrates = list(missing_in_substrates)
missing_in_substrates

['',
 '4-Hydroxybenzaldehyde',
 '(E)-2-Methylgeranyl diphosphate',
 'Neomycin B',
 '12(13)-EpOME',
 '4-Fluorobenzoyl-CoA',
 'Leu-enkephalin',
 'Acyclovir',
 'Nicotinamide nucleotide',
 'Maltotetraose',
 'Delphinidin',
 'UDPMurAc(oyl-L-Ala-D-gamma-Glu-L-Lys-D-Ala-D-Ala)',
 'L-2,4-Diaminobutanoate',
 'Hydrogen sulfide',
 'cis-Aconitate',
 '1-Myristoylglycerol 3-phosphate',
 '(S)-Reticuline',
 '(2E)-2-Hydroxypenta-2,4-dienoic acid',
 '(3R)-3-Fluoro-3-deoxy-D-arabino-heptulosonate 7-phosphate',
 'RNA',
 'Lacto-N-tetraose',
 '3-Formylcatechol',
 '1,4-beta-D-Mannan',
 'alpha-Casein',
 'Laminaribiose',
 'L-2-Aminoadipate',
 'Aniline',
 't-Butyloxycarbonyl-Phe-Ser-Arg-4-methylcoumarin-7-ylamide',
 'N-Methyldihydronicotinamide',
 '2-Hydroxycaproate',
 'Starch',
 '12-Hydroxydodecanoic acid',
 'L-Kynurenine',
 'R-(-)-3-Methylbutan-2-ol',
 'Glutathione ethyl ester-methylglyoxal hemithioacetal',
 'Linoleate',
 'Cyanamide',
 'O-Acetyl-ADP-ribose',
 'Cephalexin',
 'Boldenone',
 '3-O-Methyl-D-glucose',
 '(S)-alpha-Cyano(6-methoxy-2-naphthyl)-methyl-(2S)-2-(4-chlorophenyl)-3-methyl butanoate',
 'Ala-Tyr',
 'L-Lysinyl-L-phenylalanine',
 'Benzydamine',
 '3-Methylcyclohexanone',
 'Lys-Ile-Val-Lys-Cys-Phe-Leu-Cys-Gly-Lys',
 'p-Nitrophenyl-beta-D-xylopyranoside',
 '15-HPETE',
 '1-Indanole',
 'Chondroitin 4-sulfate',
 'p-Nitrophenylthymidine phosphate',
 '(1,4-alpha-D-Galacturonosyl)n',
 'p-Tosyl-L-arginine methyl ester',
 'XLLG-beta-CNP',
 '(S)-1-Pyrroline-5-carboxylate',
 'Tetrachloro-1,4-benzoquinone',
 '3,4-Dehydro-L-proline',
 'N-Acetyl-Lys-p-nitrophenylalanyl-Ala-amide',
 'Guanine',
 'Chitobiose',
 'Piperonal',
 '3,22-Dioxo-chol-4-ene-24-oyl-CoA',
 'Potassium ferrocyanide',
 '3-Chloro-D-alanine',
 '2-Aminobenzoyl-KLRSLKQ-N-(2,4-dinitrophenyl)ethylenediamine',
 'Maltopentaose',
 'trans-Cinnamate',
 '4-Methylumbelliferyl-2-deoxy-3-O-(beta-D-galactopyranosyl)-2-trifluoroacetamido-beta-D-glucopyranoside',
 '2-Naphthaldehyde',
 "2'-Deoxycytidine 5'-diphosphoramidate",
 'gamma-L-Glutamyl-L-cysteine',
 'Benzyloxycarbonyl-Phe-Arg-p-nitroanilide',
 'D-Mannose',
 'N-Acetyl-Lys-p-nitrophenylalanyl-amide',
 'GDP-2-fluoro-alpha-D-mannose',
 'Adenylyl-molybdopterin',
 '1-Arachidonoyl-sn-glycerol 3-phosphate',
 'Arabinogalactan',
 'GRGGFGGRGGFRGGRGG-NH2',
 'Reactive blue 5',
 '4-Methylcyclohexanol',
 '3-Oxopalmitoyl-CoA',
 'L-Alanyl-D-glutamate',
 'Biopterin',
 'Glutathionylated 2-mercaptoethanol',
 'Maltulose',
 '2-Methyl-5-hydroxy-1,4-naphthoquinone',
 'N-Succinyl-L-serine',
 'Sinapyl alcohol',
 'gamma-Cyclodextrin',
 'N-Acetylglucosamine 6-phosphate',
 'N-Succinyl-LL-2,6-diaminoheptanedioate',
 'Adipate',
 'Trypanothione-methylglyoxal hemithioacetal',
 '(S)-2-Methylbutanoyl-CoA',
 'But-2-enoyl-[acyl-carrier protein]',
 '4-Methylumbelliferyl-2-acetamido-2-deoxy-3-O-(beta-D-galactopyranosyl)-beta-D-glucopyranoside',
 'Acetoacetyl-S-homopantetheine 12-pivalate',
 '2-Fluoro-trans-cinnamate',
 'L-Rhamnose',
 '2-Oxoadipate',
 '1-Penten-3-one',
 'L-Arabinose',
 'DNA containing thymine glycol',
 'dTDP',
 'UDP-N-acetylmuramoyl-L-alanine',
 'Acetamide',
 'Malondialdehyde',
 '1-Propanol',
 'Cytosine (in DNA)',
 'Ubiquinol',
 'Obtusifoliol',
 'Furylpropionyl-CoA',
 'Ca2+',
 '(NAcGlc-NAcMur-L-Ala-D-Glu-DAP-D-Ala)2',
 'Bromoacetate',
 'Benzoyl phosphate',
 '2,4-Dichlorophenol',
 '5-O-(1-Carboxyvinyl)-3-phosphoshikimate',
 'ABZ-Dap(O2(Cbz))-Dap(Cbz)-Dap(GO1)-Arg-ANB-NH2',
 'Ala-Ala-Phe-7-Amino-4-methylcoumarin',
 'L-Ribulose 5-phosphate',
 '6-Benzylaminopurine riboside monophosphate',
 'N-Formyl-Met-Leu-Phe',
 'Methylamine',
 '(-)-Fenchone',
 'tRNA',
 'C6-4-Nitrobenzo-2-oxa-1,3-diazole-glucosylceramide',
 'Arsenate',
 '6-beta-(1-Hydroxy-1-methylethyl)-penicillanate',
 'L-Valine',
 'N-(3-Oxooctanoyl)homoserine lactone',
 '3-Bromobenzaldehyde',
 '5-Aminopentanoate',
 'Prephenate',
 'S-Sulfo-L-cysteine',
 'dTDP-4-dehydro-beta-L-rhamnose',
 '(+)-anti-BPDE',
 'Phenacetin',
 'Leu-enkephalinamide',
 'Methyl sinapate',
 '1-Bromopropane',
 '2-Hydroxyacetophenone',
 '2,3-Diaminopropanoate',
 "4'''-Demalonylsalvianin",
 '(6E,10E)-Geranyllinalool',
 '(S)-p-Nitro-2-bromo-1-phenylethanol',
 "3-Oxo-2-(2'-pentenyl)-cyclopentane-1-octanoic acid",
 '4-Hydroxy-3-methoxy-benzenemethanol',
 'D-Arabinose 5-phosphate',
 'Cefixime',
 '3-Hydroxyphenylacetyl-CoA',
 'L-Methionine',
 'Adrenocorticotropic hormone 1-39',
 '(-)-Borneol',
 'Proline',
 'Naringenin 7-O-beta-D-glucoside',
 'Holo-[acyl-carrier protein]',
 'Succinyl-YVAD-p-nitroanilide',
 '(S)-2-Acetolactate',
 'ent-Kaurene',
 'D-Erythronic acid',
 '1-Oleoyl-lysophosphatidate',
 '1-Bromo-2,3-propandiol',
 'S-(Hydroxymethyl)glutathione',
 'L-alpha-Aminobutyrate',
 'Tryptamine',
 'Gly-Tyr',
 '4-Benzyloxy-indole',
 'Butyrophenone',
 'S-(Hercyn-2-yl)-L-cysteine S-oxide',
 '2-Acetylpyrrole',
 'Proteine tyrosine phosphate',
 'N2-Acetyl-L-lysine',
 'Ferricytochrome b5',
 'Molybdate',
 'Deoxyadenosine',
 'N-Acetyl-L-alanine',
 'Reduced acceptor',
 'Dodecanoyl ethanolamide',
 'O-Phospho-4-hydroxy-L-threonine',
 '(S)-2-Chloro-1-phenylethanol',
 '(R)-Indan-1-ol',
 'L-Tagatose',
 'D-Glucosamine 1-phosphate',
 'cis-Cypermethrin',
 'Acetylthiocholine',
 'Methylglutaryl-CoA',
 '2,5-Dinitrophenyl-beta-D-xylopyranoside',
 'Acetate',
 'Aklavinone',
 '4-Methoxyphenylglyoxal',
 '2-Phenylacetamide',
 'Glutathione isopropyl ester-methylglyoxal hemithioacetal',
 '2-Aminobenzoyl-KHRSSKQ-N-(2,4-dinitrophenyl)ethylenediamine',
 '20alpha-Hydroxy-5beta-pregnan-3-one',
 '4-Nitrobutyryl-CoA',
 'N-Acetyl-D-galactosamine',
 'Diglucosylglycerate',
 'cis-3-Bromoacrylic acid',
 'Phenol',
 '3beta-Hydroxyandrost-5-en-17-one 3-sulfate',
 '2-Oxovaline',
 'D-Sorbose',
 'Neryl diphosphate',
 'Propionylthiocholine',
 '3-Pyridinealdehyde-NAD+',
 'N-Formyl-Nle-Arg-NH2',
 'S-(-)-trans-Bicyclo[2.2.1]heptanol',
 '2,4-Dimethyl-3-pentanone',
 'Benzoyl-Gly-thioglycolate',
 '2-Nitropropane',
 'Sinapoyl-CoA',
 '(R)-S-Lactoylglutathione',
 'IC-asc-C9',
 'Cyclohex-2-enone',
 'Holo-[carboxylase]',
 'DNA containing 5,6-dihydroxycytosine',
 'D-Tartrate',
 'D-Talitol',
 'Columbianetin',
 'CDP-methyl phosphate',
 'Reduced glutathione',
 'Gly-Ala-Gly',
 'Bradykinin',
 'Citrate',
 '3-[4-(Benzyloxy)-3-methoxyphenyl]-3-hydroxy-2-(2-methoxyphenoxy)propyl(methyl-4-O-methyl-alpha-D-glucopyranosid)uronate',
 '3-Hydroxy-3-methylglutaryl-CoA',
 'L-Aspartate',
 'Benzoate',
 '1-Palmitoylglycerol 3-phosphate',
 '(R)-alpha-Cyano(6-methoxy-2-naphthyl)-methyl-(1R)-cis-3-(2,2-dichlorovinyl)-2,2-dimethylcyclopropane carboxylate',
 '5-Thioglucose',
 'Sudan Orange G',
 'L-Arginine',
 'Peptide E',
 'Propanoate',
 '(S)-alpha-Cyano(6-methoxy-2-naphthyl)-methyl-(2R)-2-(4-chlorophenyl)-3-methyl butanoate',
 'L-Homoserine isopropyl ester',
 'S-Lactoylglutathione',
 '3alpha,7alpha-Dihydroxy-5beta-cholestane',
 '4-epi-Eremophilene',
 '2,3-Dihydro-2,3-dihydroxybenzoyl-CoA',
 'Asp-Pro-Arg-7-Amino-4-methylcoumarin',
 'beta-Casomorphin',
 '2,3-Dichloro-1,4-naphthoquinone',
 'Xylohexaose',
 '7,8-Diaminononanoate',
 '2-Hydroxyhexanoate',
 'L-Alanyl-D-glutamine',
 'Poly(ethylene terephthalate)',
 'Resmethrin',
 '2,4-Dinitrophenyl-beta-cellobioside',
 '4-Carboxy-4-hydroxy-2-oxoadipate',
 'L-Seryl-tRNA(Ala)',
 'Oxalate',
 "Quercetin-3,4'-diglucoside",
 '2-Methylene-1,3-propanediol',
 "Guanosine 3'-diphosphate 5'-triphosphate",
 '1-Pyrroline-4S-hydroxy-2-carboxylate',
 '2-Aminobenzoyl-LLRSSKQ-N-(2,4-dinitrophenyl)ethylenediamine',
 '1,2-Diselenolane-3-pentanoic acid',
 '3-Aminopropanol',
 '6,8-Difluoro-4-methylumbelliferyl phosphate',
 '2-Aminobenzoyl-KQRSSKQ-N-(2,4-dinitrophenyl)ethylenediamine',
 '24-Methylene lophenol',
 '4-Guanidino-3-nitrobenzoic acid',
 'L-Ascorbate',
 '4-Phospho-L-malate',
 'Cellohexaose',
 '2-Aminobenzoyl-HLRFSKQ-N-(2,4-dinitrophenyl)ethylenediamine',
 'Hemin',
 'beta-D-Fructose 6-phosphate',
 'Thiocyanate',
 'Tetrafluoro-1,4-benzoquinone',
 'Isorhamnetin',
 '5beta-Pregnan-3alpha,21-diol-20-one',
 'Scopoletin',
 '(-)-alpha-Thujone',
 'Rubusoside',
 'Benzylpenicilloic acid',
 'Guanidinoacetate',
 'L-Histidine nicotianamine',
 '2-Butanol',
 'Cytochrome c',
 'O-Demethylfonsecin',
 'Acetoacetyl-CoA',
 'Carbenicillin',
 'trans-Dec-2-enoyl-CoA',
 "3-Oxo-2-(2'-pentenyl)-cyclopentane-1-hexanoic acid",
 '5alpha-Androstane-3beta-ol-17-one',
 'Menadione',
 'N6-(delta2-Isopentenyl)-adenine',
 '4-Nitrophenyl-beta-D-xylobioside',
 '1,2,3-Tribromopropane',
 'Creosol',
 'D-Seryl-D-alanine',
 'Sarcosine',
 'Xanthohumol',
 'Nicotinamide hypoxanthine dinucleotide',
 '4-Chlorophenylglyoxal',
 'HTDDEM-pT-P-pY-VATR',
 'Electron-transferring flavoprotein',
 '2,4-Dimethylphenylglyoxal',
 'Valencene',
 'Lys-des-Arg9-bradykinin',
 'Sucrose 6-phosphate',
 'Isomaltose',
 '2-Dehydro-3-deoxy-L-galactonate',
 '3-Hydroxypropanoate',
 'H-Pro-Phe-Arg-7-amino-4-methylcoumarin',
 'Riboflavin',
 "2(S)-[Guanosyl-5'-(phosphorylamino)]-3-(3-indolyl)propionic acid methyl ester",
 'Hydrosulfide',
 'Riboflavin-5-phosphate',
 'Shikimate',
 't-Butyloxycarbonyl-Val-Leu-Lys-7-amino-4-methylcoumarin',
 'Prostaglandin H2',
 'Uridylyl-[protein-PII]',
 'dTDP-4-amino-4,6-dideoxy-D-glucose',
 'Prostaglandin E2',
 'D-Glyceraldehyde 3-phosphate',
 '4-Coumaroylshikimate',
 'Sialyl-alpha-(2,3)-lactose',
 'N-(tert-Butyloxycarbonyl)-DL-homoserine lactone',
 'Guaiacol',
 'N-Succinyl-L-tyrosine',
 'beta-1,4-Hexa-(N-acetyl-D-glucosamine)',
 '8-hydroxy-dATP',
 '1-Naphthylbutanoic acid',
 '2-Aminobenzoyl-GLRSSKQ-N-(2,4-dinitrophenyl)ethylenediamine',
 '1,4-Benzoquinone',
 'Pseudouridine',
 'Pelargonidin',
 'Androst-5-ene-3beta,17alpha-diol',
 'N-Acetylglucosamine malate',
 '2-Chloro-trans-cinnamate',
 'UDP-N-acetylmuramate',
 '2-Hydroxy-3-methoxybenzyl alcohol',
 'N-Acetyl-D-glucosamine 1-phosphate',
 'Octenoyl-CoA',
 '2-Aminobenzoyl-KLRVSKQ-N-(2,4-dinitrophenyl)ethylenediamine',
 'D-Alanyl-D-serine',
 'Galactitol',
 'N-Acetyl-D-glucosamine',
 'Stearoyl-CoA',
 'Asp-Pro-4-Nitroanilide',
 'Carbon disulfide',
 '2(S)-Amino-4-[(2S,4S)-2,4,5-trihydroxy-3-oxo-pentylsulfanyl]-butyric acid',
 '3,4-Dinitrophenyl-3-O-beta-cellobiosyl-beta-D-glucoside',
 "4-Methylumbelliferyl-beta-D-N,N',N''-triacetylchitotrioside",
 'Squalene',
 'Gly-Ala-Ala',
 '(R)-5-Diphosphomevalonate',
 '4-Chlorobenzoyl-CoA',
 'Loganate',
 '4-Hydroxybenzyladenine',
 'Glucomannan',
 '3,5-Dihydroxyphenylacetyl-CoA',
 'Cefpirome',
 'S-(-)-1-Phenylethanol',
 '(22S)-22-Hydroxycampest-4-en-3-one',
 '(5Z,13E)-11alpha-Hydroxy-9,15-dioxoprost-13-enoate',
 '3-Deoxy-D-galactose',
 'L-Alanine',
 '13-Methyl-tetradecanoic acid',
 'Spermidine',
 'Phloretin',
 'Gly-Pro-4-Nitroanilide',
 'Double-stranded DNA',
 '4-Methylumbelliferyl-beta-D-xylobioside',
 '2-Hydroxy-6-oxo-6-ethyl-2,4-dienoate',
 'DL-beta-Phenylserine',
 'D-Galactose',
 'L-Ornithine',
 '2-Aminobenzoyl-KLRQSKQ-N-(2,4-dinitrophenyl)ethylenediamine',
 '4-Bromophenylglyoxal',
 '1,2-Dihydroxyhex-1-en-3-one',
 '9,10-Phenanthroquinone',
 'Met-4-methylcoumaryl-7-amide',
 'Isomalbrancheamide B',
 '(1S)-(+)-Camphorquinone',
 'N1,N11-Diethylnorspermine',
 'Succinyl-Ala-Ala-Pro-Met-p-nitroanilide',
 'D-Alanyl-D-2-hydroxybutanoate',
 '2-Aminobenzoyl-ALRFSKQ-N-(2,4-dinitrophenyl)ethylenediamine',
 'p-Nitrophenyl-N-acetyl-beta-D-galactosaminide',
 '2,3-Dihydroxytoluene',
 '4-Chloroindole',
 'p-Nitrobenzaldehyde',
 'N-Succinyl-L-isoleucine',
 '1,6-Anhydro-N-acetyl-beta-muramate',
 'GM3',
 'Succinyl-Ala-Ala-Pro-Ala-p-nitroanilide',
 'Cholecystokinin (13-33)',
 'Ecgonine methyl ester',
 '3-Hydroxy-1H-quinolin-4-one',
 'UDP-kanosamine',
 'Arg-Pro-4-Nitroanilide',
 'Campesterol',
 'L-ddCDP',
 'trans-Pent-2-enoyl-CoA',
 'Arg-Gly-Phe',
 'Glucosylceramide',
 'trans-Tetradec-2-enoyl-CoA',
 'Methyl beta-D-galactoside',
 'Benzoyl-CoA',
 'delta1-Piperideine-2-carboxylate',
 '1,3-Dichloropropane',
 'D-Sorbitol',
 'D-Phe-Pip-Arg-p-nitroanilide',
 'D-Allitol',
 'Hexyl-1-nitronate',
 'D-2-Hydroxyvalerate',
 'Phosphonomycin',
 'Acetoacetyl-10-bis-demethylpantetheine 11-pivaloate',
 'Met-Phe',
 '3,5-Diiodo-L-tyrosine',
 'Cyclohexane carboxaldehyde',
 "[2-(3-Indolyl)-1-ethyl]phosphoramidic acid 5'-(1-&#946",
 'Carboxymethylcellulose',
 'Cyclophosphamide',
 "5'-Methylthioinosine",
 'D-Val-Leu-Lys-p-nitroanilide',
 'Tricaprilin',
 'S-3,3-Dimethylbutyl thioacetate',
 'Histone H3-K4',
 'Tetra-N-acetylchitotetraose',
 'Phenylacetic acid',
 '3,4-Dichlorobenzaldehyde',
 'L-Tyrosine',
 'N-Heptyl-beta-D-glucoside',
 '2,6-Dichlorobenzaldehyde',
 '2-Methylbutanal',
 'Chorismate',
 'Thiamine triphosphate',
 'N-Succinyl-L-histidine',
 "syn-[3'-D]Columbianetin",
 'Salicylate',
 'o-Nitrophenyl-beta-D-glucopyranoside',
 '1-R,S-cis-Permethrin',
 "4-Hydroxybenzoyl-(3'-dephospho)-CoA",
 '2-Aminobenzoyl-KLRNSKQ-N-(2,4-dinitrophenyl)ethylenediamine',
 'UDP-3-O-(3-hydroxytetradecanoyl)-N-acetylglucosamine',
 'S-Formylglutathione',
 '2-Bromoethanol',
 '6-Deoxocathasterone',
 'n-Butyraldoxime',
 '5-Valerolactone',
 'Maltose',
 'Lactosamine',
 '1,2-Dibromopropane',
 'Butanoyl-CoA',
 'Dimethylglyoxal',
 'p-Nitrophenyl laurate',
 'N-Benzoyl-L-arginine ethyl ester',
 'Lactose',
 '4-Nitrophenyl alpha-D-xyloside',
 'Homoisocitrate',
 'L-Arabitol',
 'Pyridoxine phosphate',
 'Pentanal',
 'D-Methionine',
 '7,12-Dimethylbenzo[a]anthracene',
 'Ethylamine',
 '9(10)-EpOME',
 "5-Amino-6-(5'-phosphoribitylamino)uracil",
 'GalNAc-alpha1-Ser',
 'tRNA(Trp)',
 '(R)-3-Hydroxybutanoate',
 'D-Leucine',
 'Pyridoxal',
 'N-Formyl-Met-Leu-Glu',
 'Tetrahydropteroyl hepta-L-glutamate',
 'L-Leucinyl-p-nitroanilide',
 '2-Amino-3,8-dimethylimidazo[4,5-f]quinoxaline',
 'N(omega)-methyl-L-Arginine',
 'L-Methionine S-oxide',
 'cis-(1R,2S)-2-Amino-1-tetralol',
 '5-Formyltetrahydrofolate',
 'N-Acetyl-D-glucosaminyldiphospho-(6Z,10Z)-2,6,10-trimethyl-2,6,10-tridecatriene',
 'Indan-1-ol',
 'Cyclohex-2-en-1-ol',
 'Isomaltoheptaose',
 'Dexamethasone-Cephem-Methotrexate',
 'Trioleoylglycerol',
 '(-)-Menthol',
 '3-Indoleacetonitrile',
 'Hydrocaffeic acid',
 'Acetyl phosphate',
 'Acc-tRNA(Lys)',
 'alpha-Oxo-benzeneacetic acid',
 'Dithionitrobenzoic acid',
 'Carbobenzoxy-Gly-Gly-Leu',
 'p65',
 '2,4,6-Trimethylphenylglyoxal',
 '1,2-Dideoxy-D-hexulose 6-phosphate',
 '5-(Aziridin-1-yl)-2,4-dinitrobenzamide',
 'Daunorubicin',
 'Arabinose',
 'Leucrose',
 '3-Hydroxy-5,9,17-trioxo-4,5:9,10-disecoandrosta-1(10),2-dien-4-oate',
 '5alpha-Androstane-3,17-dione',
 '2-Deoxy-D-glucose',
 'Hip-His-Leu-NH2',
 'N-Benzyloxycarbonyl-L-homoserine lactone',
 'L-Xylulose',
 'GDP-L-galactose',
 '(R)-Prunasin',
 'Xylotriose',
 'Indole-3-ethanol',
 '17alpha-Hydroxyprogesterone',
 'Benzo[a]pyrene-7,8-diol',
 'N-Formyl-L-methionine',
 '2-Dehydro-D-gluconate',
 'Amidorphin',
 'Hip-His-Leu',
 'Gly-Gly-Ala',
 '2-Aminobenzoyl-KWRSSKQ-N-(2,4-dinitrophenyl)ethylenediamine',
 'L-Lysine',
 "RNA terminal-2',3'-cyclic-phosphate",
 '6-alpha-(1-Hydroxyethyl)-penicillanate',
 'N-(2-Furyl)acryloylpenicillin',
 'L-Homoserine',
 'p-Nitrophenyl lacto-N-bioside',
 'Tributyrin',
 '1-Phenyl-1,2-propanedione',
 'Quercetin 4-O-beta-D-glucoside',
 '4-Methylumbelliferyl acetate',
 'Galactosylceramide',
 'alpha-Cyclodextrin',
 'Oxaloacetate',
 'Chlorzoxazone',
 "2'-(4-Methylumbelliferyl)-alpha-D-N-acetylneuraminic acid",
 'D-Glyceraldehyde',
 '3-Hydroxyacetophenone',
 '5-(Dimethylamino)naphthalene-1-sulfonyl-Pro-Leu-Ala-Leu-Trp-Ala-Arg',
 'Piperacillin',
 'DNA containing 5-hydroxyuracil',
 'Thebaine',
 'Androst-4-ene-3,17-dione',
 'R-(-)-Octan-2-ol',
 '3-Hydroxybenzyladenine',
 '2-Aminobenzoyl-KLRSHKQ-N-(2,4-dinitrophenyl)ethylenediamine',
 '2-Aminobenzoyl-KYRSSKQ-N-(2,4-dinitrophenyl)ethylenediamine',
 '2,4,5-Trichlorophenol',
 '5-Hydroxy-1,4-naphthoquinone',
 '2-Phosphonoacetaldehyde',
 '2-Aminobenzoyl-KLRFSRQ-N-(2,4-dinitrophenyl)ethylenediamine',
 'Anthraniloyl-CoA',
 '4-Ethylphenyl phosphate',
 'CDPethanolamine',
 'UDP-N-acetylmuramoyl-L-alanyl-D-glutamyl-L-ornithyl-D-alanyl-D-alanine',
 'Sphinganine',
 '(R)-Pantothenate',
 'beta-D-Glucose 1-phosphate',
 'Anthranilate',
 'N-Succinyl-2,6-diaminoheptanedioate',
 'Acenaphthenequinone',
 'D-Fructose 1-phosphate',
 'Lys-Ile-Val-Lys-Cys-Phe-Lys-Cys-Gly-Lys',
 '5,10-Methenyltetrahydrofolate',
 '4-Trifluoromethylbenzoyl-CoA',
 '2-Keto-4-methylhexanoic acid',
 'Dopamine',
 'UDPgalactose',
 'UDPglucuronate',
 'L-Lysyl-p-nitroanilide',
 'beta-D-Glucosyl-1,4-N-acetyl-D-glucosamine',
 'Big endothelin-1',
 'Formyl-L-methionyl peptide',
 'Kanamycin A',
 '2-Deoxy-6-phospho-D-gluconate',
 '1-Linoleoyl-2-hydroxyglycerophosphocholine',
 'Histone',
 '10-Formyl-5-deazafolate',
 'Diphospho-myo-inositol pentakisphosphate',
 'L-Phenylalanine',
 'Crotonoyl-CoA',
 'Precorrin 8X',
 'Coniferyl acetate',
 'DED(EDANS)KPILFFRLGK(Dabcyl)E',
 'Ethanol',
 'L-Leucylglycine',
 'Protein histidine',
 'Poly(butylene succinate-co-adipate)',
 '4-Nitrophenyl-alpha-D-maltoheptaoside-4,6-O-ethylidene',
 'Ac-Arg-Pro-Leu-Glu-Ser-Asn-Ala-Val',
 '3-alpha-Hydroxy-5-epiaristolochene',
 '2-Aminobenzoyl-NLRSSKQ-N-(2,4-dinitrophenyl)ethylenediamine',
 'Pyridoxal phosphate',
 '5-Methyl-2-hexanone',
 'Kaempferol 3-O-beta-D-galactoside',
 'delta(L-2-Aminoadipyl)-L-cysteinyl-D-valine',
 'N-Acetyl-Ala-Ala-Lys-p-nitrophenylalanyl-amide',
 'tRNA(Arg)',
 'Palmitoyl-CoA',
 '(S)-Lipoic acid',
 '5alpha-Pregnan-3alpha,21-diol-20-one',
 'Histone-L-lysine',
 'Cefuroxime',
 'Xylitol',
 'D-Glucosone',
 'S-Propyl thioacetate',
 'Taxifolin',
 'Ala-Gly-Gly',
 'Angiotensin II',
 'Tyr-Ala',
 '(S)-alpha-Cyano(6-methoxy-2-naphthyl)-methyl-(1S)-cis-3-(2,2-dichlorovinyl)-2,2-dimethylcyclopropane carboxylate',
 'Tetrahydropteroyl di-L-glutamate',
 'N-Formyl-Nle-Ala-Ser',
 'Bis(2-hydroxyethyl) terephthalate',
 'Glycylpeptide',
 '2-Hydroxyisocaproate',
 'Hydrogencarbonate',
 'Bocillin FL',
 'Retinol',
 '(R,R)-Butane-2,3-diol',
 '5alpha-Pregnane-3,20-dione',
 'D-Tagatose 1,6-bisphosphate',
 'Mannose-alpha-1,3-glucose-beta-1,4-glucose-diphosphate-polyisoprenyl',
 'Myristic acid',
 'Isopentenyl diphosphate',
 'alpha-D-Glucose 1-phosphate',
 '1,3-beta-D-Glucan',
 'L-Analyl-RNA',
 '3-Phosphohydroxypyruvate',
 'Reduced methyl viologen',
 'Phenylpyruvate',
 'Stearoyl-[acyl-carrier protein]',
 '2-Amino-1-methyl-6-phenylimidazo[4,5-b]pyridine',
 'Phosphotyrosine',
 'L-Alanyl-L-phenylalanine',
 "[2-(3-Indolyl)-1-ethyl]phosphoramidic acid 5'-(7-benzylguanosyl) ester",
 'Palmitoleoyl-CoA',
 'L-Methionine (R)-S-oxide',
 'Methylglyoxal',
 '4-Hydroxy-4-methyl-2-oxoglutarate',
 '2-Heptyl-4-hydroxyquinoline-N-oxide',
 '4-Methylumbelliferyl-3-O-beta-cellotriosyl-beta-D-glucoside',
 'Cob(II)alamin',
 'L-Malate',
 'Acetophenone',
 "[2-(3-Indolyl)-1(S)-carbamoylethyl]phosphoramidic acid 5'-adenosyl ester",
 'Hexanoate',
 'Azocasein',
 'N-Formyl-Phe-Ala-Ser',
 'Dihydroxyacetone',
 'D-Phenylglycine methyl ester',
 'des-Arg9-bradykinin',
 'trans-Resveratrol',
 '3alpha-Hydroxy-5alpha-pregnan-20-one',
 'Arg-Pro-Pro',
 'Adenylylsulfate',
 'Di[3-deoxy-D-manno-octulosonyl]-lipid IV(A)',
 'N-Acetyl-Lys-p-nitrophenylalanyl-Ala-Ala-amide',
 'Acetoacetate',
 '(22S,24R)-22-Hydroxy-5alpha-ergostan-3-one',
 'Cephaloridin',
 'tRNA containing 5-methylaminomethyl-2-(S-geranyl)thiouridine',
 '4-Hydroxycinnamyl aldehyde',
 'Phosphate',
 'Arg-Glu(5-[(2-aminoethyl)amino]-naphthalene-1-sulfonic acid)-Glu-Val-Asn-Leu-Asp-Ala-Glu-Phe-Lys(4-(4-dimethylaminophenylazo)benzoic acid)-Arg',
 'Dehydroluciferyladenylate',
 'Monoacetylphloroglucinol',
 '5-Aminolevulinate',
 '2-Hydroxy-5-methyl-6-oxo-2,4-dienoate',
 'Xylose',
 'Glutaryl-CoA',
 '2,4-Dinitrophenyl phosphate',
 'Carboxymethylbenzoylaminothioacetate',
 '(R)-alpha-Cyano(6-methoxy-2-naphthyl)-methyl-(1S)-cis-3-(2,2-dichlorovinyl)-2,2-dimethylcyclopropane carboxylate',
 'L-Homocysteine',
 'AK88',
 'L-Alanyl-L-histidine',
 'Aspartate',
 'D-Erythrose',
 'Pro-Phe',
 'D-Alanine',
 'N-Succinyl-L-threonine',
 '1-Chloro-2,4-dinitrobenzene',
 'L-Alanyl-L-lysine',
 'Butirosin A',
 'Rebaudioside E',
 'Lys-Ile-Val-Lys-Cys-Phe-Phe-Cys-Gly-Lys',
 'Adriamycin',
 '(Alginate)n',
 'Cyanin',
 'GDPmannose',
 "5'-D-Valyl-floxuridine",
 'Epiandrosterone',
 'Magnesium protoporphyrin',
 '4-Methylumbelliferone sulfate',
 'p-Nitrophenyl-beta-L-arabinopyranoside',
 '3-Methoxyphenylglyoxal',
 'Dithioerythritol',
 'Trimethylamine',
 'D-Tryptophan',

In [ ]:
def get_cid_from_google(substrate):
    try:
        # PubChem PUG REST API URL
        search_url = f"https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/{quote_plus(substrate)}/cids/JSON"
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }
        response = requests.get(search_url, headers=headers)
        
        if response.status_code != 200:
            print(f"Failed to get response for {substrate}")
            return None
            
        data = response.json()
        if 'IdentifierList' in data and 'CID' in data['IdentifierList']:
            cids = data['IdentifierList']['CID']
            if cids:
                return str(cids[0]) 
                
        print(f"Could not find CID in PubChem for {substrate}")
        return None
        
    except Exception as e:
        print(f"Error getting CID from PubChem for {substrate}: {str(e)}")
        return None

def get_smiles(cid):
    try:
        # PubChem PUG REST API URL
        url = f"https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/{cid}/property/IsomericSMILES,CanonicalSMILES/JSON"
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }
        
        response = requests.get(url, headers=headers)
        if response.status_code != 200:
            return None, None
            
        data = response.json()
        if 'PropertyTable' in data and 'Properties' in data['PropertyTable']:
            properties = data['PropertyTable']['Properties'][0]
            return properties.get('IsomericSMILES'), properties.get('CanonicalSMILES')
            
        return None, None
        
    except Exception as e:
        print(f"Error getting SMILES for CID {cid}: {str(e)}")
        return None, None

In [ ]:
for substrate in missing_in_substrates:
    try:
        cid = get_cid_from_google(substrate)
        
        if cid is not None:
            isomeric_smiles, canonical_smiles = get_smiles(cid)

            if isomeric_smiles is not None:
                new_row = {
                    'substrate': substrate,
                    'isomeric_smiles': isomeric_smiles,
                    'canonical_smiles': canonical_smiles
                }
                substrates = pd.concat([substrates, pd.DataFrame([new_row])], ignore_index=True)
                print(f"Added: {substrate}")
    except:
        print(f"Error ({substrate}): {e}")

print(f"Final substrate length: {len(substrates)}")

Failed to get response for
Failed to get response for (E)-2-Methylgeranyl diphosphate
Failed to get response for Neomycin B
Failed to get response for Nicotinamide nucleotide
Failed to get response for Hydrogen sulfide
Failed to get response for 1-Myristoylglycerol 3-phosphate
Failed to get response for (2E)-2-Hydroxypenta-2,4-dienoic acid
Failed to get response for (3R)-3-Fluoro-3-deoxy-D-arabino-heptulosonate 7-phosphate
Failed to get response for RNA
Failed to get response for 3-Formylcatechol
Failed to get response for alpha-Casein
Failed to get response for t-Butyloxycarbonyl-Phe-Ser-Arg-4-methylcoumarin-7-ylamide
Failed to get response for N-Methyldihydronicotinamide
Failed to get response for Starch
Failed to get response for 12-Hydroxydodecanoic acid
Failed to get response for R-(-)-3-Methylbutan-2-ol
Failed to get response for Glutathione ethyl ester-methylglyoxal hemithioacetal
Failed to get response for (S)-alpha-Cyano(6-methoxy-2-naphthyl)-methyl-(2S)-2-(4-chlorophenyl)-3-methyl butanoate
Failed to get response for L-Lysinyl-L-phenylalanine
Failed to get response for Lys-Ile-Val-Lys-Cys-Phe-Leu-Cys-Gly-Lys
Failed to get response for Chondroitin 4-sulfate
Failed to get response for p-Nitrophenylthymidine phosphate
Failed to get response for p-Tosyl-L-arginine methyl ester
Failed to get response for XLLG-beta-CNP
Failed to get response for N-Acetyl-Lys-p-nitrophenylalanyl-Ala-amide
Failed to get response for 3,22-Dioxo-chol-4-ene-24-oyl-CoA
Failed to get response for Potassium ferrocyanide
Failed to get response for 2-Aminobenzoyl-KLRSLKQ-N-(2,4-dinitrophenyl)ethylenediamine
Failed to get response for 4-Methylumbelliferyl-2-deoxy-3-O-(beta-D-galactopyranosyl)-2-trifluoroacetamido-beta-D-glucopyranoside
Failed to get response for 2'-Deoxycytidine 5'-diphosphoramidate
Failed to get response for Benzyloxycarbonyl-Phe-Arg-p-nitroanilide
Failed to get response for N-Acetyl-Lys-p-nitrophenylalanyl-amide
Failed to get response for GDP-2-fluoro-alpha-D-mannose
Failed to get response for 1-Arachidonoyl-sn-glycerol 3-phosphate
Failed to get response for Arabinogalactan
Failed to get response for GRGGFGGRGGFRGGRGG-NH2
Failed to get response for Reactive blue 5
Failed to get response for Glutathionylated 2-mercaptoethanol
Failed to get response for Sinapyl alcohol
Failed to get response for N-Acetylglucosamine 6-phosphate
Failed to get response for Trypanothione-methylglyoxal hemithioacetal
Failed to get response for But-2-enoyl-[acyl-carrier protein]
Failed to get response for 4-Methylumbelliferyl-2-acetamido-2-deoxy-3-O-(beta-D-galactopyranosyl)-beta-D-glucopyranoside
Failed to get response for Acetoacetyl-S-homopantetheine 12-pivalate
Failed to get response for 2-Fluoro-trans-cinnamate
Failed to get response for DNA containing thymine glycol
Failed to get response for Cytosine (in DNA)
Failed to get response for Furylpropionyl-CoA
Failed to get response for (NAcGlc-NAcMur-L-Ala-D-Glu-DAP-D-Ala)2
Failed to get response for Benzoyl phosphate
Failed to get response for ABZ-Dap(O2(Cbz))-Dap(Cbz)-Dap(GO1)-Arg-ANB-NH2
Failed to get response for Ala-Ala-Phe-7-Amino-4-methylcoumarin
Failed to get response for L-Ribulose 5-phosphate
Failed to get response for 6-Benzylaminopurine riboside monophosphate
Failed to get response for tRNA
Failed to get response for C6-4-Nitrobenzo-2-oxa-1,3-diazole-glucosylceramide
Failed to get response for 6-beta-(1-Hydroxy-1-methylethyl)-penicillanate
Failed to get response for N-(3-Oxooctanoyl)homoserine lactone
Failed to get response for Methyl sinapate
Failed to get response for (S)-p-Nitro-2-bromo-1-phenylethanol
Failed to get response for 3-Oxo-2-(2'-pentenyl)-cyclopentane-1-octanoic acid
Failed to get response for D-Arabinose 5-phosphate
Failed to get response for Adrenocorticotropic hormone 1-39
Failed to get response for Naringenin 7-O-beta-D-glucoside
Failed to get response for Holo-[acyl-carrier protein]
Failed to get response for Succinyl-YVAD-p-nitroanilide
Failed to get response for D-Erythronic acid
Failed to get response for 1-Bromo-2,3-propandiol
Failed to get response for S-(Hercyn-2-yl)-L-cysteine S-oxide
Failed to get response for Proteine tyrosine phosphate
Failed to get response for Ferricytochrome b5
Failed to get response for Reduced acceptor
Failed to get response for Dodecanoyl ethanolamide
Failed to get response for (R)-Indan-1-ol
Failed to get response for D-Glucosamine 1-phosphate
Failed to get response for 2,5-Dinitrophenyl-beta-D-xylopyranoside
Failed to get response for Glutathione isopropyl ester-methylglyoxal hemithioacetal
Failed to get response for 2-Aminobenzoyl-KHRSSKQ-N-(2,4-dinitrophenyl)ethylenediamine
Failed to get response for 4-Nitrobutyryl-CoA
Failed to get response for Diglucosylglycerate
Failed to get response for cis-3-Bromoacrylic acid
Failed to get response for 3beta-Hydroxyandrost-5-en-17-one 3-sulfate
Failed to get response for 2-Oxovaline
Failed to get response for Neryl diphosphate
Failed to get response for 3-Pyridinealdehyde-NAD+
Failed to get response for N-Formyl-Nle-Arg-NH2
Failed to get response for S-(-)-trans-Bicyclo[2.2.1]heptanol
Failed to get response for Benzoyl-Gly-thioglycolate
Failed to get response for Holo-[carboxylase]
Failed to get response for DNA containing 5,6-dihydroxycytosine
Failed to get response for CDP-methyl phosphate
Failed to get response for Reduced glutathione
Failed to get response for 3-[4-(Benzyloxy)-3-methoxyphenyl]-3-hydroxy-2-(2-methoxyphenoxy)propyl(methyl-4-O-methyl-alpha-D-glucopyranosid)uronate
Failed to get response for 1-Palmitoylglycerol 3-phosphate
Failed to get response for (R)-alpha-Cyano(6-methoxy-2-naphthyl)-methyl-(1R)-cis-3-(2,2-dichlorovinyl)-2,2-dimethylcyclopropane carboxylate
Failed to get response for 5-Thioglucose
Failed to get response for Sudan Orange G
Failed to get response for Peptide E
Failed to get response for (S)-alpha-Cyano(6-methoxy-2-naphthyl)-methyl-(2R)-2-(4-chlorophenyl)-3-methyl butanoate
Failed to get response for L-Homoserine isopropyl ester
Failed to get response for 2,3-Dihydro-2,3-dihydroxybenzoyl-CoA
Failed to get response for Asp-Pro-Arg-7-Amino-4-methylcoumarin
Failed to get response for Xylohexaose
Failed to get response for Poly(ethylene terephthalate)
Failed to get response for 2,4-Dinitrophenyl-beta-cellobioside
Failed to get response for L-Seryl-tRNA(Ala)
Failed to get response for Guanosine 3'-diphosphate 5'-triphosphate
Failed to get response for 1-Pyrroline-4S-hydroxy-2-carboxylate
Failed to get response for 2-Aminobenzoyl-LLRSSKQ-N-(2,4-dinitrophenyl)ethylenediamine
Failed to get response for 1,2-Diselenolane-3-pentanoic acid
Failed to get response for 6,8-Difluoro-4-methylumbelliferyl phosphate
Failed to get response for 2-Aminobenzoyl-KQRSSKQ-N-(2,4-dinitrophenyl)ethylenediamine
Failed to get response for 24-Methylene lophenol
Failed to get response for 4-Guanidino-3-nitrobenzoic acid
Failed to get response for 4-Phospho-L-malate
Failed to get response for 2-Aminobenzoyl-HLRFSKQ-N-(2,4-dinitrophenyl)ethylenediamine
Failed to get response for beta-D-Fructose 6-phosphate
Failed to get response for Benzylpenicilloic acid
Failed to get response for L-Histidine nicotianamine
Failed to get response for Cytochrome c
Failed to get response for 3-Oxo-2-(2'-pentenyl)-cyclopentane-1-hexanoic acid
Failed to get response for 5alpha-Androstane-3beta-ol-17-one
Failed to get response for Nicotinamide hypoxanthine dinucleotide
Failed to get response for HTDDEM-pT-P-pY-VATR
Failed to get response for Electron-transferring flavoprotein
Failed to get response for Lys-des-Arg9-bradykinin
Failed to get response for Sucrose 6-phosphate
Failed to get response for H-Pro-Phe-Arg-7-amino-4-methylcoumarin
Failed to get response for 2(S)-[Guanosyl-5'-(phosphorylamino)]-3-(3-indolyl)propionic acid methyl ester
Failed to get response for t-Butyloxycarbonyl-Val-Leu-Lys-7-amino-4-methylcoumarin
Failed to get response for Prostaglandin H2
Failed to get response for Uridylyl-[protein-PII]
Failed to get response for Prostaglandin E2
Failed to get response for D-Glyceraldehyde 3-phosphate
Failed to get response for Sialyl-alpha-(2,3)-lactose
Failed to get response for N-(tert-Butyloxycarbonyl)-DL-homoserine lactone
Failed to get response for beta-1,4-Hexa-(N-acetyl-D-glucosamine)
Failed to get response for 1-Naphthylbutanoic acid
Failed to get response for 2-Aminobenzoyl-GLRSSKQ-N-(2,4-dinitrophenyl)ethylenediamine
Failed to get response for N-Acetylglucosamine malate
Failed to get response for 2-Chloro-trans-cinnamate
Failed to get response for 2-Hydroxy-3-methoxybenzyl alcohol
Failed to get response for N-Acetyl-D-glucosamine 1-phosphate
Failed to get response for 2-Aminobenzoyl-KLRVSKQ-N-(2,4-dinitrophenyl)ethylenediamine
Failed to get response for Asp-Pro-4-Nitroanilide
Failed to get response for Carbon disulfide
Failed to get response for 2(S)-Amino-4-[(2S,4S)-2,4,5-trihydroxy-3-oxo-pentylsulfanyl]-butyric acid
Failed to get response for 3,4-Dinitrophenyl-3-O-beta-cellobiosyl-beta-D-glucoside
Failed to get response for 4-Hydroxybenzyladenine
Failed to get response for S-(-)-1-Phenylethanol
Failed to get response for 13-Methyl-tetradecanoic acid
Failed to get response for Gly-Pro-4-Nitroanilide
Failed to get response for Double-stranded DNA
Failed to get response for 4-Methylumbelliferyl-beta-D-xylobioside
Failed to get response for 2-Hydroxy-6-oxo-6-ethyl-2,4-dienoate
Failed to get response for 2-Aminobenzoyl-KLRQSKQ-N-(2,4-dinitrophenyl)ethylenediamine
Failed to get response for Met-4-methylcoumaryl-7-amide
Failed to get response for Isomalbrancheamide B
Failed to get response for D-Alanyl-D-2-hydroxybutanoate
Failed to get response for 2-Aminobenzoyl-ALRFSKQ-N-(2,4-dinitrophenyl)ethylenediamine
Failed to get response for GM3
Failed to get response for Succinyl-Ala-Ala-Pro-Ala-p-nitroanilide
Failed to get response for Cholecystokinin (13-33)
Failed to get response for Ecgonine methyl ester
Failed to get response for Arg-Pro-4-Nitroanilide
Failed to get response for L-ddCDP
Failed to get response for trans-Pent-2-enoyl-CoA
Failed to get response for Glucosylceramide
Failed to get response for Methyl beta-D-galactoside
Failed to get response for D-Phe-Pip-Arg-p-nitroanilide
Failed to get response for Hexyl-1-nitronate
Failed to get response for Acetoacetyl-10-bis-demethylpantetheine 11-pivaloate
Failed to get response for Cyclohexane carboxaldehyde
Failed to get response for [2-(3-Indolyl)-1-ethyl]phosphoramidic acid 5'-(1-&#946
Failed to get response for Carboxymethylcellulose
Failed to get response for S-3,3-Dimethylbutyl thioacetate
Failed to get response for Histone H3-K4
Failed to get response for Phenylacetic acid
Failed to get response for N-Heptyl-beta-D-glucoside
Failed to get response for Thiamine triphosphate
Failed to get response for syn-[3'-D]Columbianetin
Failed to get response for o-Nitrophenyl-beta-D-glucopyranoside
Failed to get response for 1-R,S-cis-Permethrin
Failed to get response for 4-Hydroxybenzoyl-(3'-dephospho)-CoA
Failed to get response for 2-Aminobenzoyl-KLRNSKQ-N-(2,4-dinitrophenyl)ethylenediamine
Failed to get response for p-Nitrophenyl laurate
Failed to get response for N-Benzoyl-L-arginine ethyl ester
Failed to get response for 4-Nitrophenyl alpha-D-xyloside
Failed to get response for Pyridoxine phosphate
Failed to get response for GalNAc-alpha1-Ser
Failed to get response for tRNA(Trp)
Failed to get response for N-Formyl-Met-Leu-Glu
Failed to get response for Tetrahydropteroyl hepta-L-glutamate
Failed to get response for L-Leucinyl-p-nitroanilide
Failed to get response for L-Methionine S-oxide
Failed to get response for cis-(1R,2S)-2-Amino-1-tetralol
Failed to get response for N-Acetyl-D-glucosaminyldiphospho-(6Z,10Z)-2,6,10-trimethyl-2,6,10-tridecatriene
Failed to get response for Dexamethasone-Cephem-Methotrexate
Failed to get response for Hydrocaffeic acid
Failed to get response for Acetyl phosphate
Failed to get response for Acc-tRNA(Lys)
Failed to get response for alpha-Oxo-benzeneacetic acid
Failed to get response for Dithionitrobenzoic acid
Failed to get response for Carbobenzoxy-Gly-Gly-Leu
Failed to get response for 1,2-Dideoxy-D-hexulose 6-phosphate
Failed to get response for Hip-His-Leu-NH2
Failed to get response for N-Benzyloxycarbonyl-L-homoserine lactone
Failed to get response for 2-Aminobenzoyl-KWRSSKQ-N-(2,4-dinitrophenyl)ethylenediamine
Failed to get response for RNA terminal-2',3'-cyclic-phosphate
Failed to get response for 6-alpha-(1-Hydroxyethyl)-penicillanate
Failed to get response for N-(2-Furyl)acryloylpenicillin
Failed to get response for p-Nitrophenyl lacto-N-bioside
Failed to get response for Quercetin 4-O-beta-D-glucoside
Failed to get response for 4-Methylumbelliferyl acetate
Failed to get response for 2'-(4-Methylumbelliferyl)-alpha-D-N-acetylneuraminic acid
Failed to get response for 5-(Dimethylamino)naphthalene-1-sulfonyl-Pro-Leu-Ala-Leu-Trp-Ala-Arg
Failed to get response for DNA containing 5-hydroxyuracil
Failed to get response for R-(-)-Octan-2-ol
Failed to get response for 3-Hydroxybenzyladenine
Failed to get response for 2-Aminobenzoyl-KLRSHKQ-N-(2,4-dinitrophenyl)ethylenediamine
Failed to get response for 2-Aminobenzoyl-KYRSSKQ-N-(2,4-dinitrophenyl)ethylenediamine
Failed to get response for 2-Aminobenzoyl-KLRFSRQ-N-(2,4-dinitrophenyl)ethylenediamine
Failed to get response for 4-Ethylphenyl phosphate
Failed to get response for UDP-N-acetylmuramoyl-L-alanyl-D-glutamyl-L-ornithyl-D-alanyl-D-alanine
Failed to get response for beta-D-Glucose 1-phosphate
Failed to get response for N-Succinyl-2,6-diaminoheptanedioate
Failed to get response for D-Fructose 1-phosphate
Failed to get response for Lys-Ile-Val-Lys-Cys-Phe-Lys-Cys-Gly-Lys
Failed to get response for 4-Trifluoromethylbenzoyl-CoA
Failed to get response for 2-Keto-4-methylhexanoic acid
Failed to get response for L-Lysyl-p-nitroanilide
Failed to get response for beta-D-Glucosyl-1,4-N-acetyl-D-glucosamine
Failed to get response for Big endothelin-1
Failed to get response for Formyl-L-methionyl peptide
Failed to get response for Kanamycin A
Failed to get response for 1-Linoleoyl-2-hydroxyglycerophosphocholine
Failed to get response for Histone
Failed to get response for 10-Formyl-5-deazafolate
Failed to get response for Diphospho-myo-inositol pentakisphosphate
Failed to get response for Precorrin 8X
Failed to get response for Coniferyl acetate
Failed to get response for DED(EDANS)KPILFFRLGK(Dabcyl)E
Failed to get response for Protein histidine
Failed to get response for Poly(butylene succinate-co-adipate)
Failed to get response for 4-Nitrophenyl-alpha-D-maltoheptaoside-4,6-O-ethylidene
Failed to get response for Ac-Arg-Pro-Leu-Glu-Ser-Asn-Ala-Val
Failed to get response for 3-alpha-Hydroxy-5-epiaristolochene
Failed to get response for 2-Aminobenzoyl-NLRSSKQ-N-(2,4-dinitrophenyl)ethylenediamine
Failed to get response for Pyridoxal phosphate
Failed to get response for Kaempferol 3-O-beta-D-galactoside
Failed to get response for N-Acetyl-Ala-Ala-Lys-p-nitrophenylalanyl-amide
Failed to get response for tRNA(Arg)
Failed to get response for (S)-Lipoic acid
Failed to get response for Histone-L-lysine
Failed to get response for S-Propyl thioacetate
Failed to get response for Angiotensin II
Failed to get response for (S)-alpha-Cyano(6-methoxy-2-naphthyl)-methyl-(1S)-cis-3-(2,2-dichlorovinyl)-2,2-dimethylcyclopropane carboxylate
Failed to get response for Tetrahydropteroyl di-L-glutamate
Failed to get response for N-Formyl-Nle-Ala-Ser
Failed to get response for Bis(2-hydroxyethyl) terephthalate
Failed to get response for Bocillin FL
Failed to get response for D-Tagatose 1,6-bisphosphate
Failed to get response for Mannose-alpha-1,3-glucose-beta-1,4-glucose-diphosphate-polyisoprenyl
Failed to get response for Myristic acid
Failed to get response for Isopentenyl diphosphate
Failed to get response for alpha-D-Glucose 1-phosphate
Failed to get response for L-Analyl-RNA
Failed to get response for Reduced methyl viologen
Failed to get response for Stearoyl-[acyl-carrier protein]
Failed to get response for [2-(3-Indolyl)-1-ethyl]phosphoramidic acid 5'-(7-benzylguanosyl) ester
Failed to get response for L-Methionine (R)-S-oxide
Failed to get response for 4-Methylumbelliferyl-3-O-beta-cellotriosyl-beta-D-glucoside
Failed to get response for [2-(3-Indolyl)-1(S)-carbamoylethyl]phosphoramidic acid 5'-adenosyl ester
Failed to get response for N-Formyl-Phe-Ala-Ser
Failed to get response for D-Phenylglycine methyl ester
Failed to get response for Di[3-deoxy-D-manno-octulosonyl]-lipid IV(A)
Failed to get response for N-Acetyl-Lys-p-nitrophenylalanyl-Ala-Ala-amide
Failed to get response for tRNA containing 5-methylaminomethyl-2-(S-geranyl)thiouridine
Failed to get response for 4-Hydroxycinnamyl aldehyde
Failed to get response for Arg-Glu(5-[(2-aminoethyl)amino]-naphthalene-1-sulfonic acid)-Glu-Val-Asn-Leu-Asp-Ala-Glu-Phe-Lys(4-(4-dimethylaminophenylazo)benzoic acid)-Arg
Failed to get response for Dehydroluciferyladenylate
Failed to get response for 2-Hydroxy-5-methyl-6-oxo-2,4-dienoate
Failed to get response for 2,4-Dinitrophenyl phosphate
Failed to get response for Carboxymethylbenzoylaminothioacetate
Failed to get response for (R)-alpha-Cyano(6-methoxy-2-naphthyl)-methyl-(1S)-cis-3-(2,2-dichlorovinyl)-2,2-dimethylcyclopropane carboxylate
Failed to get response for AK88
Failed to get response for Butirosin A
Failed to get response for Rebaudioside E
Failed to get response for Lys-Ile-Val-Lys-Cys-Phe-Phe-Cys-Gly-Lys
Failed to get response for 5'-D-Valyl-floxuridine
Failed to get response for Magnesium protoporphyrin
Failed to get response for 4-Methylumbelliferone sulfate
Failed to get response for p-Nitrophenyl-beta-L-arabinopyranoside
Failed to get response for Phosphocarrier protein Crh
Failed to get response for 2-Aminobenzoyl-KTRSSKQ-N-(2,4-dinitrophenyl)ethylenediamine
Failed to get response for Leaf alcohol
Failed to get response for 2-Aminobenzoyl-LPETGG-diaminopropionic acid(dinitrophenyl)-NH2
Failed to get response for (3S)-3-Fluoro-3-deoxy-D-arabino-heptulosonate 7-phosphate
Failed to get response for tRNA(His)
Failed to get response for N-Acetyl-Ala-Lys-p-nitrophenylalanyl-amide
Failed to get response for 3-Phospho-D-glyceroyl phosphate
Failed to get response for Succinate semialdehyde
Failed to get response for Asn-Ala-Arg-ACC
Failed to get response for Cyanidin 3-O-(6-O-malonyl-beta-D-glucoside)
Failed to get response for 2-Aminobenzoyl-QLRSSKQ-N-(2,4-dinitrophenyl)ethylenediamine
Failed to get response for 2-Aminobenzoyl-KLRISKQ-N-(2,4-dinitrophenyl)ethylenediamine
Failed to get response for 3-Methoxybenzyladenine
Error getting CID from PubChem for CDP-L-glutamine: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Failed to get response for 2',3'-Cyclic GMP
Failed to get response for N(omega)-amino-L-Arginine
Failed to get response for [2-(3-Indolyl)-1(S)-carbamoylethyl]-(S)-thiophosphoramidic acid 5'-guanosyl ester
Failed to get response for Cytochrome c3+
Failed to get response for Caffeic aldehyde
Failed to get response for Rebaudioside A
Failed to get response for Hydroxyethyl disulfide
Failed to get response for 1,N6-ethenoadenine containing DNA
Failed to get response for D-4-Hydroxyphenylglycine amide
Failed to get response for Rosmaric acid
Failed to get response for N-Succinyl-L-asparagine
Failed to get response for 4-Bromophenyl-beta-D-galactopyranoside
Failed to get response for tRNA guanine
Failed to get response for Isovanillic acid
Failed to get response for Ethyl 2-phenylacetate
Failed to get response for 2-Aminobenzoyl-KLRSPKQ-N-(2,4-dinitrophenyl)ethylenediamine
Failed to get response for (R)-Norprotosinomenine
Failed to get response for Isopentenyladenine riboside monophosphate
Failed to get response for 2-Aminobenzoyl-KLRFFKQ-N-(2,4-dinitrophenyl)ethylenediamine
Failed to get response for tRNA(Tyr)
Failed to get response for N-Formyl-Met-Ala-O-
Failed to get response for Neurotensin (1-8)

In [ ]:
def process_substrate_smiles(substrate):
    substrate_parts = [s.strip() for s in substrate.split(";")]
    
    isomeric_smiles = []
    canonical_smiles = []
    for part in substrate_parts:
        matching_row = substrates[substrates['substrate'] == part]
        
        if not matching_row.empty:
            isomeric = matching_row.iloc[0]['isomeric_smiles']
            canonical = matching_row.iloc[0]['canonical_smiles']
            
            if isomeric is not None:
                isomeric_smiles.append(isomeric)
                canonical_smiles.append(canonical)
        else:
            isomeric_smiles = []
            canonical_smiles = []

    try:
        isomeric_smiles = ";".join(isomeric_smiles)
        canonical_smiles = ";".join(canonical_smiles)
        return isomeric_smiles, canonical_smiles
    except:
        return None, None

In [26]:
isomeric_smiles, canonical_smiles = [], []

df = df.reset_index(drop=True)

for i in range(len(df)):
    isomeric, canonical = process_substrate_smiles(df.loc[i, 'substrate'])
    isomeric_smiles.append(isomeric)
    canonical_smiles.append(canonical)

df['isomeric_smiles'] = isomeric_smiles
df['canonical_smiles'] = canonical_smiles

In [ ]:
print('Data with no substrate SMILES: ', len(df[df['isomeric_smiles'].isna()]))

Substrate SMILES가 없는 데이터 수:  86

## Add mutation information to sequence

In [ ]:
def apply_mutations(sequence, mutation_info):
    mutations = mutation_info.split('/')
    seq_len = len(sequence)

    for mutation in mutations:
        wt_aa = mutation[0]
        mt_aa = mutation[-1]
        pos = int(mutation[1:-1])-1 # Python number

        try:
            if sequence[pos] == wt_aa:
                sequence = sequence[:pos] + mt_aa + sequence[pos+1:]
            elif sequence[pos+1] == wt_aa:
                sequence = sequence[:pos+1] + mt_aa + sequence[pos+2:]
            elif sequence[pos+2] == wt_aa:
                sequence = sequence[:pos+2] + mt_aa + sequence[pos+3:]
            else:
                print(f'Pos {pos} does not match wildtype amino acid {wt_aa}, {sequence[pos]}')
                print(f"Mutation {mutation} does not match wildtype amino acid {wt_aa} at position {pos}")
                print(f"Sequence: {sequence}")
                return None
        except:
            print(f"Mutation {mutation} is out of sequence length | sequence length: {seq_len}")
            return None

    if len(sequence) != seq_len:
        print(f"Sequence length changed from {seq_len} to {len(sequence)}")
        print(f"Sequence: {sequence}")
        return None
    
    return sequence

In [29]:
df = df.reset_index(drop=True)

In [30]:
df.head()

,Enzyme Variant,ec_number,uniprot,organism,temperature,pH,parameter.name,parameter.type,parameter.associatedSpecies,parameter.startValue,parameter.endValue,parameter.standardDeviation,parameter.unit,substrate,sequence,type,mutation,turnover_number,isomeric_smiles,canonical_smiles
0,mutant MDH G81S,1.1.99.31,P20932,Pseudomonas putida,20.0,7.5,kcat,kcat,NaN,2.80,NaN,1E-1,s^(-1),Riboflavin-5-phosphate;(S)-Mandelate,MSQNLFNVEDYRKLRQKRLPKMVYDYLEGGAEDEYGVKHNRDVFQQ...,mutant,G81S,2.80,C1=CC=C(C=C1)[C@@H](C(=O)[O-])O,C1=CC=C(C=C1)C(C(=O)[O-])O
1,mutant MDH G81V,1.1.99.31,P20932,Pseudomonas putida,20.0,7.5,kcat,kcat,NaN,0.05,NaN,4E-3,s^(-1),Riboflavin-5-phosphate;(S)-Mandelate,MSQNLFNVEDYRKLRQKRLPKMVYDYLEGGAEDEYGVKHNRDVFQQ...,mutant,G81V,0.05,C1=CC=C(C=C1)[C@@H](C(=O)[O-])O,C1=CC=C(C=C1)C(C(=O)[O-])O
2,mutant MDH G81D,1.1.99.31,P20932,Pseudomonas putida,20.0,7.5,kcat,kcat,NaN,0.11,NaN,4E-3,s^(-1),Riboflavin-5-phosphate;(S)-Mandelate,MSQNLFNVEDYRKLRQKRLPKMVYDYLEGGAEDEYGVKHNRDVFQQ...,mutant,G81D,0.11,C1=CC=C(C=C1)[C@@H](C(=O)[O-])O,C1=CC=C(C=C1)C(C(=O)[O-])O
3,wildtype DHFR,1.5.1.3,P0ABQ4,Escherichia coli,15.0,7.0,k_cat,kcat,NaN,6.18,NaN,-,s^(-1),NADPH;Dihydrofolate;H+,MISLIAALAVDRVIGMENAMPWNLPADLAWFKRNTLNKPVIMGRHT...,wildtype,None,6.18,,
4,mutant DHFR W30A,1.5.1.3,P0ABQ4,Escherichia coli,15.0,7.0,k_cat,kcat,NaN,14.50,NaN,-,s^(-1),NADPH;Dihydrofolate;H+,MISLIAALAVDRVIGMENAMPWNLPADLAWFKRNTLNKPVIMGRHT...,mutant,W30A,14.50,,

In [31]:
sequences = []

df = df.dropna(subset=['sequence']).reset_index(drop=True)

for i in range(len(df)):
    if pd.notna(df.loc[i, 'mutation']):
        seq = apply_mutations(df.iloc[i]['sequence'], df.iloc[i]['mutation'])
        sequences.append(seq)
    else:
        sequences.append(df.loc[i, 'sequence'])

Pos 1698 does not match wildtype amino acid K, V
Mutation K1699A does not match wildtype amino acid K at position 1698
Sequence: MEEVVIAGMSGKLPESENLQEFWDNLIGGVDMVTDDDRRWKAGLYGLPRRSGKLKDLSRFDASFFGVHPKQAHTMDPQLRLLLEVTYEAIVDGGINPDSLRGTHTGVWVGVSGSETSEALSRDPETLVGYSMVGCQRAMMANRLSFFFDFRGPSIALDTACSSSLMALQNAYQAIHSGQCPAAIVGGINVLLKPNTSVQFLRLGMLSPEGTCKAFDTAGNGYCRSEGVVAVLLTKKSLARRVYATILNAGTNTDGFKEQGVTFPSGDIQEQLIRSLYQSAGVAPESFEYIEAHGTGTKVGDPQELNGITRALCATRQEPLLIGSTKSNMGHPEPASGLAALAKVLLSLEHGLWAPNLHFHSPNPEIPALLDGRLQVVDQPLPVRGGNVGINSFGFGGSNVHIILRPNTQPPPAPAPHATLPRLLRASGRTPEAVQKLLEQGLRHSQDLAFLSMLNDIAAVPATAMPFRGYAVLGGERGGPEVQQVPAGERPLWFICSGMGTQWRGMGLSLMRLDRFRDSILRSDEAVKPFGLKVSQLLLSTDESTFDDIVHSFVSLTAIQIGLIDLLSCMGLRPDGIVGHSLGEVACGYADGCLSQEEAVLAAYWRGQCIKEAHLPPGAMAAVGLSWEECKQRCPPGVVPACHNSKDTVTISGPQAPVFEFVEQLRKEGVFAKEVRTGGMAFHSYFMEAIAPPLLQELKKVIREPKPRSARWLSTSIPEAQWHSSLARTSSAEYNVNNLVSPVLFQEALWHVPEHAVVLEIAPHALLQAVLKRGLKPSCTIIPLMKKDHRDNLEFFLAGIGRLHLSGIDANPNALFPPVEFPAPRGTPLISPLIKWDHSLAWDVPAAEDFPNGSGSPSAAIYNIDTSSESPDHYLVDHTLDGRVLFPATGYLSIVWKTLARALGLGVEQLPVVFEDVVLHQATILPKTGTVSLEVRLLEASRAFEVSENGNLVVSGKVYQWDDPDPRLFDHPESPTPNPTEPLFLAQAEVYKELRLRGYDYGPHFQGILEASLEGDSGRLLWKDNWVSFMDTMLQMSILGSAKHGLYLPTRVTAIHIDPATHRQKLYTLQDKAQVADVVVSRWLRVTVAGGVHISGLHTESAPRRQQEQQVPILEKFCFTPHTEEGCLSERAALQEELQLCKGLVQALQTKVTQQGLKMVVPGLDGAQIPRDPSQQELPRLLSAACRLQLNGNLQLELAQVLAQERPKLPEDPLLSGLLDSPALKACLDTAVENMPSLKMKVVEVLAGHGHLYSRIPGLLSPHPLLQLSYTATDRHPQALEAAQAELQQHDVAQGQWDPADPAPSALGSADLLVCNCAVAALGDPASALSNMVAALREGGFLLLHTLLRGHPLGDIVAFLTSTEPQYGQGILSQDAWESLFSRVSLRLVGLKKSFYGSTLFLCRRPTPQDSPIFLPVDDTSFRWVESLKGILADEDSSRPVWLKAINCATSGVVGLVNCLRREPGGNRLRCVLLSNLSSTSHVPEVDPGSAELQKVLQGDLVMNVYRDGAWGAFRHFLLEEDKPEEPTAHAFVSTLTRGDLSSIRWVCSSLRHAQPTCPGAQLCTVYYASLNFRDIMLATGKLSPDAIPGKWTSQDSLLGMEFSGRDASGKRVMGLVPAKGLATSVLLSPDFLWDVPSNWTLEEAASVPVVYSTAYYALVVRGRVRPGETLLIHSGSGGVGQAAIAIALSLGCRVFTTVGSAEKRAYLQARFPQLDSTSFANSRDTSFEQHVLWHTGGKGVDLVLNSLAEEKLQASVRCLATHGRFLEIGKFDLSQNHPLGMAIFLKNVTFHGVLLDAFFNESSADWREVWALVQAGIRDGVVRPLKCTVFHGAQVEDAFRYMAQGKHIGKVVVQVLAEEPEAVLKGAKPKLMSAISKTFCPAHKSYIIAGGLGGFGLELAQWLIQRGVQKLVLTSRSGIRTGYQAKQVRRWRRQGVQVQVSTSNISSLEGARGLIAEAAQLGPVGGVFNLAVVLRDGLLENQTPEFFQDVCKPKYSGTLNLDRVTREACPELDYFVVFSSVSCGRGNAGQSNYGFANSAMERICEKRRHEGLPGLAVQWGAIGDVGILVETMSTNDTIVSGTLPQRMASCLEVLDLFLNQPHMVLSSFVLAEKAAAYRDRDSQRDLVEAVAHILGIRDLAAVNLDSSLADLGLDSLMSVEVRQTLERELNLVLSVREVRQLTLRKLQELSSKADEASELACPTPKEDGLAQQQTQLNLRSLLVNPEGPTLMRLNSVQSSERPLFLVHPIEGSTTVFHSLASRLSIPTYGLQCTRAAPLDSIHSLAAYYIDCIRQVQPEGPYRVAGYSYGACVAFEMCSQLQAQQSPAPTHNSLFLFDGSPTYVLAYTQSYRAKLTPGCEAEAETEAICFFVQQFTDMEHNRVLEALLPLKGLEERVAAAVDLIIKSHQGLDRQELSFAARSFYYKLRAAEQYTPKAKYHGNVMLLRAKTGGAYGEDLGADYNLSQVCDGKVSVHVIEGDHRTLLEGSGLESIISIIHSSLAEPRVSVREG
Pos 1698 does not match wildtype amino acid K, V
Mutation K1699Q does not match wildtype amino acid K at position 1698
Sequence: MEEVVIAGMSGKLPESENLQEFWDNLIGGVDMVTDDDRRWKAGLYGLPRRSGKLKDLSRFDASFFGVHPKQAHTMDPQLRLLLEVTYEAIVDGGINPDSLRGTHTGVWVGVSGSETSEALSRDPETLVGYSMVGCQRAMMANRLSFFFDFRGPSIALDTACSSSLMALQNAYQAIHSGQCPAAIVGGINVLLKPNTSVQFLRLGMLSPEGTCKAFDTAGNGYCRSEGVVAVLLTKKSLARRVYATILNAGTNTDGFKEQGVTFPSGDIQEQLIRSLYQSAGVAPESFEYIEAHGTGTKVGDPQELNGITRALCATRQEPLLIGSTKSNMGHPEPASGLAALAKVLLSLEHGLWAPNLHFHSPNPEIPALLDGRLQVVDQPLPVRGGNVGINSFGFGGSNVHIILRPNTQPPPAPAPHATLPRLLRASGRTPEAVQKLLEQGLRHSQDLAFLSMLNDIAAVPATAMPFRGYAVLGGERGGPEVQQVPAGERPLWFICSGMGTQWRGMGLSLMRLDRFRDSILRSDEAVKPFGLKVSQLLLSTDESTFDDIVHSFVSLTAIQIGLIDLLSCMGLRPDGIVGHSLGEVACGYADGCLSQEEAVLAAYWRGQCIKEAHLPPGAMAAVGLSWEECKQRCPPGVVPACHNSKDTVTISGPQAPVFEFVEQLRKEGVFAKEVRTGGMAFHSYFMEAIAPPLLQELKKVIREPKPRSARWLSTSIPEAQWHSSLARTSSAEYNVNNLVSPVLFQEALWHVPEHAVVLEIAPHALLQAVLKRGLKPSCTIIPLMKKDHRDNLEFFLAGIGRLHLSGIDANPNALFPPVEFPAPRGTPLISPLIKWDHSLAWDVPAAEDFPNGSGSPSAAIYNIDTSSESPDHYLVDHTLDGRVLFPATGYLSIVWKTLARALGLGVEQLPVVFEDVVLHQATILPKTGTVSLEVRLLEASRAFEVSENGNLVVSGKVYQWDDPDPRLFDHPESPTPNPTEPLFLAQAEVYKELRLRGYDYGPHFQGILEASLEGDSGRLLWKDNWVSFMDTMLQMSILGSAKHGLYLPTRVTAIHIDPATHRQKLYTLQDKAQVADVVVSRWLRVTVAGGVHISGLHTESAPRRQQEQQVPILEKFCFTPHTEEGCLSERAALQEELQLCKGLVQALQTKVTQQGLKMVVPGLDGAQIPRDPSQQELPRLLSAACRLQLNGNLQLELAQVLAQERPKLPEDPLLSGLLDSPALKACLDTAVENMPSLKMKVVEVLAGHGHLYSRIPGLLSPHPLLQLSYTATDRHPQALEAAQAELQQHDVAQGQWDPADPAPSALGSADLLVCNCAVAALGDPASALSNMVAALREGGFLLLHTLLRGHPLGDIVAFLTSTEPQYGQGILSQDAWESLFSRVSLRLVGLKKSFYGSTLFLCRRPTPQDSPIFLPVDDTSFRWVESLKGILADEDSSRPVWLKAINCATSGVVGLVNCLRREPGGNRLRCVLLSNLSSTSHVPEVDPGSAELQKVLQGDLVMNVYRDGAWGAFRHFLLEEDKPEEPTAHAFVSTLTRGDLSSIRWVCSSLRHAQPTCPGAQLCTVYYASLNFRDIMLATGKLSPDAIPGKWTSQDSLLGMEFSGRDASGKRVMGLVPAKGLATSVLLSPDFLWDVPSNWTLEEAASVPVVYSTAYYALVVRGRVRPGETLLIHSGSGGVGQAAIAIALSLGCRVFTTVGSAEKRAYLQARFPQLDSTSFANSRDTSFEQHVLWHTGGKGVDLVLNSLAEEKLQASVRCLATHGRFLEIGKFDLSQNHPLGMAIFLKNVTFHGVLLDAFFNESSADWREVWALVQAGIRDGVVRPLKCTVFHGAQVEDAFRYMAQGKHIGKVVVQVLAEEPEAVLKGAKPKLMSAISKTFCPAHKSYIIAGGLGGFGLELAQWLIQRGVQKLVLTSRSGIRTGYQAKQVRRWRRQGVQVQVSTSNISSLEGARGLIAEAAQLGPVGGVFNLAVVLRDGLLENQTPEFFQDVCKPKYSGTLNLDRVTREACPELDYFVVFSSVSCGRGNAGQSNYGFANSAMERICEKRRHEGLPGLAVQWGAIGDVGILVETMSTNDTIVSGTLPQRMASCLEVLDLFLNQPHMVLSSFVLAEKAAAYRDRDSQRDLVEAVAHILGIRDLAAVNLDSSLADLGLDSLMSVEVRQTLERELNLVLSVREVRQLTLRKLQELSSKADEASELACPTPKEDGLAQQQTQLNLRSLLVNPEGPTLMRLNSVQSSERPLFLVHPIEGSTTVFHSLASRLSIPTYGLQCTRAAPLDSIHSLAAYYIDCIRQVQPEGPYRVAGYSYGACVAFEMCSQLQAQQSPAPTHNSLFLFDGSPTYVLAYTQSYRAKLTPGCEAEAETEAICFFVQQFTDMEHNRVLEALLPLKGLEERVAAAVDLIIKSHQGLDRQELSFAARSFYYKLRAAEQYTPKAKYHGNVMLLRAKTGGAYGEDLGADYNLSQVCDGKVSVHVIEGDHRTLLEGSGLESIISIIHSSLAEPRVSVREG
Pos 1698 does not match wildtype amino acid K, V
Mutation K1699A does not match wildtype amino acid K at position 1698
Sequence: MEEVVIAGMSGKLPESENLQEFWDNLIGGVDMVTDDDRRWKAGLYGLPRRSGKLKDLSRFDASFFGVHPKQAHTMDPQLRLLLEVTYEAIVDGGINPDSLRGTHTGVWVGVSGSETSEALSRDPETLVGYSMVGCQRAMMANRLSFFFDFRGPSIALDTACSSSLMALQNAYQAIHSGQCPAAIVGGINVLLKPNTSVQFLRLGMLSPEGTCKAFDTAGNGYCRSEGVVAVLLTKKSLARRVYATILNAGTNTDGFKEQGVTFPSGDIQEQLIRSLYQSAGVAPESFEYIEAHGTGTKVGDPQELNGITRALCATRQEPLLIGSTKSNMGHPEPASGLAALAKVLLSLEHGLWAPNLHFHSPNPEIPALLDGRLQVVDQPLPVRGGNVGINSFGFGGSNVHIILRPNTQPPPAPAPHATLPRLLRASGRTPEAVQKLLEQGLRHSQDLAFLSMLNDIAAVPATAMPFRGYAVLGGERGGPEVQQVPAGERPLWFICSGMGTQWRGMGLSLMRLDRFRDSILRSDEAVKPFGLKVSQLLLSTDESTFDDIVHSFVSLTAIQIGLIDLLSCMGLRPDGIVGHSLGEVACGYADGCLSQEEAVLAAYWRGQCIKEAHLPPGAMAAVGLSWEECKQRCPPGVVPACHNSKDTVTISGPQAPVFEFVEQLRKEGVFAKEVRTGGMAFHSYFMEAIAPPLLQELKKVIREPKPRSARWLSTSIPEAQWHSSLARTSSAEYNVNNLVSPVLFQEALWHVPEHAVVLEIAPHALLQAVLKRGLKPSCTIIPLMKKDHRDNLEFFLAGIGRLHLSGIDANPNALFPPVEFPAPRGTPLISPLIKWDHSLAWDVPAAEDFPNGSGSPSAAIYNIDTSSESPDHYLVDHTLDGRVLFPATGYLSIVWKTLARALGLGVEQLPVVFEDVVLHQATILPKTGTVSLEVRLLEASRAFEVSENGNLVVSGKVYQWDDPDPRLFDHPESPTPNPTEPLFLAQAEVYKELRLRGYDYGPHFQGILEASLEGDSGRLLWKDNWVSFMDTMLQMSILGSAKHGLYLPTRVTAIHIDPATHRQKLYTLQDKAQVADVVVSRWLRVTVAGGVHISGLHTESAPRRQQEQQVPILEKFCFTPHTEEGCLSERAALQEELQLCKGLVQALQTKVTQQGLKMVVPGLDGAQIPRDPSQQELPRLLSAACRLQLNGNLQLELAQVLAQERPKLPEDPLLSGLLDSPALKACLDTAVENMPSLKMKVVEVLAGHGHLYSRIPGLLSPHPLLQLSYTATDRHPQALEAAQAELQQHDVAQGQWDPADPAPSALGSADLLVCNCAVAALGDPASALSNMVAALREGGFLLLHTLLRGHPLGDIVAFLTSTEPQYGQGILSQDAWESLFSRVSLRLVGLKKSFYGSTLFLCRRPTPQDSPIFLPVDDTSFRWVESLKGILADEDSSRPVWLKAINCATSGVVGLVNCLRREPGGNRLRCVLLSNLSSTSHVPEVDPGSAELQKVLQGDLVMNVYRDGAWGAFRHFLLEEDKPEEPTAHAFVSTLTRGDLSSIRWVCSSLRHAQPTCPGAQLCTVYYASLNFRDIMLATGKLSPDAIPGKWTSQDSLLGMEFSGRDASGKRVMGLVPAKGLATSVLLSPDFLWDVPSNWTLEEAASVPVVYSTAYYALVVRGRVRPGETLLIHSGSGGVGQAAIAIALSLGCRVFTTVGSAEKRAYLQARFPQLDSTSFANSRDTSFEQHVLWHTGGKGVDLVLNSLAEEKLQASVRCLATHGRFLEIGKFDLSQNHPLGMAIFLKNVTFHGVLLDAFFNESSADWREVWALVQAGIRDGVVRPLKCTVFHGAQVEDAFRYMAQGKHIGKVVVQVLAEEPEAVLKGAKPKLMSAISKTFCPAHKSYIIAGGLGGFGLELAQWLIQRGVQKLVLTSRSGIRTGYQAKQVRRWRRQGVQVQVSTSNISSLEGARGLIAEAAQLGPVGGVFNLAVVLRDGLLENQTPEFFQDVCKPKYSGTLNLDRVTREACPELDYFVVFSSVSCGRGNAGQSNYGFANSAMERICEKRRHEGLPGLAVQWGAIGDVGILVETMSTNDTIVSGTLPQRMASCLEVLDLFLNQPHMVLSSFVLAEKAAAYRDRDSQRDLVEAVAHILGIRDLAAVNLDSSLADLGLDSLMSVEVRQTLERELNLVLSVREVRQLTLRKLQELSSKADEASELACPTPKEDGLAQQQTQLNLRSLLVNPEGPTLMRLNSVQSSERPLFLVHPIEGSTTVFHSLASRLSIPTYGLQCTRAAPLDSIHSLAAYYIDCIRQVQPEGPYRVAGYSYGACVAFEMCSQLQAQQSPAPTHNSLFLFDGSPTYVLAYTQSYRAKLTPGCEAEAETEAICFFVQQFTDMEHNRVLEALLPLKGLEERVAAAVDLIIKSHQGLDRQELSFAARSFYYKLRAAEQYTPKAKYHGNVMLLRAKTGGAYGEDLGADYNLSQVCDGKVSVHVIEGDHRTLLEGSGLESIISIIHSSLAEPRVSVREG
Pos 1698 does not match wildtype amino acid K, V
Mutation K1699Q does not match wildtype amino acid K at position 1698
Sequence: MEEVVIAGMSGKLPESENLQEFWDNLIGGVDMVTDDDRRWKAGLYGLPRRSGKLKDLSRFDASFFGVHPKQAHTMDPQLRLLLEVTYEAIVDGGINPDSLRGTHTGVWVGVSGSETSEALSRDPETLVGYSMVGCQRAMMANRLSFFFDFRGPSIALDTACSSSLMALQNAYQAIHSGQCPAAIVGGINVLLKPNTSVQFLRLGMLSPEGTCKAFDTAGNGYCRSEGVVAVLLTKKSLARRVYATILNAGTNTDGFKEQGVTFPSGDIQEQLIRSLYQSAGVAPESFEYIEAHGTGTKVGDPQELNGITRALCATRQEPLLIGSTKSNMGHPEPASGLAALAKVLLSLEHGLWAPNLHFHSPNPEIPALLDGRLQVVDQPLPVRGGNVGINSFGFGGSNVHIILRPNTQPPPAPAPHATLPRLLRASGRTPEAVQKLLEQGLRHSQDLAFLSMLNDIAAVPATAMPFRGYAVLGGERGGPEVQQVPAGERPLWFICSGMGTQWRGMGLSLMRLDRFRDSILRSDEAVKPFGLKVSQLLLSTDESTFDDIVHSFVSLTAIQIGLIDLLSCMGLRPDGIVGHSLGEVACGYADGCLSQEEAVLAAYWRGQCIKEAHLPPGAMAAVGLSWEECKQRCPPGVVPACHNSKDTVTISGPQAPVFEFVEQLRKEGVFAKEVRTGGMAFHSYFMEAIAPPLLQELKKVIREPKPRSARWLSTSIPEAQWHSSLARTSSAEYNVNNLVSPVLFQEALWHVPEHAVVLEIAPHALLQAVLKRGLKPSCTIIPLMKKDHRDNLEFFLAGIGRLHLSGIDANPNALFPPVEFPAPRGTPLISPLIKWDHSLAWDVPAAEDFPNGSGSPSAAIYNIDTSSESPDHYLVDHTLDGRVLFPATGYLSIVWKTLARALGLGVEQLPVVFEDVVLHQATILPKTGTVSLEVRLLEASRAFEVSENGNLVVSGKVYQWDDPDPRLFDHPESPTPNPTEPLFLAQAEVYKELRLRGYDYGPHFQGILEASLEGDSGRLLWKDNWVSFMDTMLQMSILGSAKHGLYLPTRVTAIHIDPATHRQKLYTLQDKAQVADVVVSRWLRVTVAGGVHISGLHTESAPRRQQEQQVPILEKFCFTPHTEEGCLSERAALQEELQLCKGLVQALQTKVTQQGLKMVVPGLDGAQIPRDPSQQELPRLLSAACRLQLNGNLQLELAQVLAQERPKLPEDPLLSGLLDSPALKACLDTAVENMPSLKMKVVEVLAGHGHLYSRIPGLLSPHPLLQLSYTATDRHPQALEAAQAELQQHDVAQGQWDPADPAPSALGSADLLVCNCAVAALGDPASALSNMVAALREGGFLLLHTLLRGHPLGDIVAFLTSTEPQYGQGILSQDAWESLFSRVSLRLVGLKKSFYGSTLFLCRRPTPQDSPIFLPVDDTSFRWVESLKGILADEDSSRPVWLKAINCATSGVVGLVNCLRREPGGNRLRCVLLSNLSSTSHVPEVDPGSAELQKVLQGDLVMNVYRDGAWGAFRHFLLEEDKPEEPTAHAFVSTLTRGDLSSIRWVCSSLRHAQPTCPGAQLCTVYYASLNFRDIMLATGKLSPDAIPGKWTSQDSLLGMEFSGRDASGKRVMGLVPAKGLATSVLLSPDFLWDVPSNWTLEEAASVPVVYSTAYYALVVRGRVRPGETLLIHSGSGGVGQAAIAIALSLGCRVFTTVGSAEKRAYLQARFPQLDSTSFANSRDTSFEQHVLWHTGGKGVDLVLNSLAEEKLQASVRCLATHGRFLEIGKFDLSQNHPLGMAIFLKNVTFHGVLLDAFFNESSADWREVWALVQAGIRDGVVRPLKCTVFHGAQVEDAFRYMAQGKHIGKVVVQVLAEEPEAVLKGAKPKLMSAISKTFCPAHKSYIIAGGLGGFGLELAQWLIQRGVQKLVLTSRSGIRTGYQAKQVRRWRRQGVQVQVSTSNISSLEGARGLIAEAAQLGPVGGVFNLAVVLRDGLLENQTPEFFQDVCKPKYSGTLNLDRVTREACPELDYFVVFSSVSCGRGNAGQSNYGFANSAMERICEKRRHEGLPGLAVQWGAIGDVGILVETMSTNDTIVSGTLPQRMASCLEVLDLFLNQPHMVLSSFVLAEKAAAYRDRDSQRDLVEAVAHILGIRDLAAVNLDSSLADLGLDSLMSVEVRQTLERELNLVLSVREVRQLTLRKLQELSSKADEASELACPTPKEDGLAQQQTQLNLRSLLVNPEGPTLMRLNSVQSSERPLFLVHPIEGSTTVFHSLASRLSIPTYGLQCTRAAPLDSIHSLAAYYIDCIRQVQPEGPYRVAGYSYGACVAFEMCSQLQAQQSPAPTHNSLFLFDGSPTYVLAYTQSYRAKLTPGCEAEAETEAICFFVQQFTDMEHNRVLEALLPLKGLEERVAAAVDLIIKSHQGLDRQELSFAARSFYYKLRAAEQYTPKAKYHGNVMLLRAKTGGAYGEDLGADYNLSQVCDGKVSVHVIEGDHRTLLEGSGLESIISIIHSSLAEPRVSVREG
Pos 1698 does not match wildtype amino acid K, V
Mutation K1699A does not match wildtype amino acid K at position 1698
Sequence: MEEVVIAGMSGKLPESENLQEFWDNLIGGVDMVTDDDRRWKAGLYGLPRRSGKLKDLSRFDASFFGVHPKQAHTMDPQLRLLLEVTYEAIVDGGINPDSLRGTHTGVWVGVSGSETSEALSRDPETLVGYSMVGCQRAMMANRLSFFFDFRGPSIALDTACSSSLMALQNAYQAIHSGQCPAAIVGGINVLLKPNTSVQFLRLGMLSPEGTCKAFDTAGNGYCRSEGVVAVLLTKKSLARRVYATILNAGTNTDGFKEQGVTFPSGDIQEQLIRSLYQSAGVAPESFEYIEAHGTGTKVGDPQELNGITRALCATRQEPLLIGSTKSNMGHPEPASGLAALAKVLLSLEHGLWAPNLHFHSPNPEIPALLDGRLQVVDQPLPVRGGNVGINSFGFGGSNVHIILRPNTQPPPAPAPHATLPRLLRASGRTPEAVQKLLEQGLRHSQDLAFLSMLNDIAAVPATAMPFRGYAVLGGERGGPEVQQVPAGERPLWFICSGMGTQWRGMGLSLMRLDRFRDSILRSDEAVKPFGLKVSQLLLSTDESTFDDIVHSFVSLTAIQIGLIDLLSCMGLRPDGIVGHSLGEVACGYADGCLSQEEAVLAAYWRGQCIKEAHLPPGAMAAVGLSWEECKQRCPPGVVPACHNSKDTVTISGPQAPVFEFVEQLRKEGVFAKEVRTGGMAFHSYFMEAIAPPLLQELKKVIREPKPRSARWLSTSIPEAQWHSSLARTSSAEYNVNNLVSPVLFQEALWHVPEHAVVLEIAPHALLQAVLKRGLKPSCTIIPLMKKDHRDNLEFFLAGIGRLHLSGIDANPNALFPPVEFPAPRGTPLISPLIKWDHSLAWDVPAAEDFPNGSGSPSAAIYNIDTSSESPDHYLVDHTLDGRVLFPATGYLSIVWKTLARALGLGVEQLPVVFEDVVLHQATILPKTGTVSLEVRLLEASRAFEVSENGNLVVSGKVYQWDDPDPRLFDHPESPTPNPTEPLFLAQAEVYKELRLRGYDYGPHFQGILEASLEGDSGRLLWKDNWVSFMDTMLQMSILGSAKHGLYLPTRVTAIHIDPATHRQKLYTLQDKAQVADVVVSRWLRVTVAGGVHISGLHTESAPRRQQEQQVPILEKFCFTPHTEEGCLSERAALQEELQLCKGLVQALQTKVTQQGLKMVVPGLDGAQIPRDPSQQELPRLLSAACRLQLNGNLQLELAQVLAQERPKLPEDPLLSGLLDSPALKACLDTAVENMPSLKMKVVEVLAGHGHLYSRIPGLLSPHPLLQLSYTATDRHPQALEAAQAELQQHDVAQGQWDPADPAPSALGSADLLVCNCAVAALGDPASALSNMVAALREGGFLLLHTLLRGHPLGDIVAFLTSTEPQYGQGILSQDAWESLFSRVSLRLVGLKKSFYGSTLFLCRRPTPQDSPIFLPVDDTSFRWVESLKGILADEDSSRPVWLKAINCATSGVVGLVNCLRREPGGNRLRCVLLSNLSSTSHVPEVDPGSAELQKVLQGDLVMNVYRDGAWGAFRHFLLEEDKPEEPTAHAFVSTLTRGDLSSIRWVCSSLRHAQPTCPGAQLCTVYYASLNFRDIMLATGKLSPDAIPGKWTSQDSLLGMEFSGRDASGKRVMGLVPAKGLATSVLLSPDFLWDVPSNWTLEEAASVPVVYSTAYYALVVRGRVRPGETLLIHSGSGGVGQAAIAIALSLGCRVFTTVGSAEKRAYLQARFPQLDSTSFANSRDTSFEQHVLWHTGGKGVDLVLNSLAEEKLQASVRCLATHGRFLEIGKFDLSQNHPLGMAIFLKNVTFHGVLLDAFFNESSADWREVWALVQAGIRDGVVRPLKCTVFHGAQVEDAFRYMAQGKHIGKVVVQVLAEEPEAVLKGAKPKLMSAISKTFCPAHKSYIIAGGLGGFGLELAQWLIQRGVQKLVLTSRSGIRTGYQAKQVRRWRRQGVQVQVSTSNISSLEGARGLIAEAAQLGPVGGVFNLAVVLRDGLLENQTPEFFQDVCKPKYSGTLNLDRVTREACPELDYFVVFSSVSCGRGNAGQSNYGFANSAMERICEKRRHEGLPGLAVQWGAIGDVGILVETMSTNDTIVSGTLPQRMASCLEVLDLFLNQPHMVLSSFVLAEKAAAYRDRDSQRDLVEAVAHILGIRDLAAVNLDSSLADLGLDSLMSVEVRQTLERELNLVLSVREVRQLTLRKLQELSSKADEASELACPTPKEDGLAQQQTQLNLRSLLVNPEGPTLMRLNSVQSSERPLFLVHPIEGSTTVFHSLASRLSIPTYGLQCTRAAPLDSIHSLAAYYIDCIRQVQPEGPYRVAGYSYGACVAFEMCSQLQAQQSPAPTHNSLFLFDGSPTYVLAYTQSYRAKLTPGCEAEAETEAICFFVQQFTDMEHNRVLEALLPLKGLEERVAAAVDLIIKSHQGLDRQELSFAARSFYYKLRAAEQYTPKAKYHGNVMLLRAKTGGAYGEDLGADYNLSQVCDGKVSVHVIEGDHRTLLEGSGLESIISIIHSSLAEPRVSVREG
Pos 1698 does not match wildtype amino acid K, V
Mutation K1699Q does not match wildtype amino acid K at position 1698
Sequence: MEEVVIAGMSGKLPESENLQEFWDNLIGGVDMVTDDDRRWKAGLYGLPRRSGKLKDLSRFDASFFGVHPKQAHTMDPQLRLLLEVTYEAIVDGGINPDSLRGTHTGVWVGVSGSETSEALSRDPETLVGYSMVGCQRAMMANRLSFFFDFRGPSIALDTACSSSLMALQNAYQAIHSGQCPAAIVGGINVLLKPNTSVQFLRLGMLSPEGTCKAFDTAGNGYCRSEGVVAVLLTKKSLARRVYATILNAGTNTDGFKEQGVTFPSGDIQEQLIRSLYQSAGVAPESFEYIEAHGTGTKVGDPQELNGITRALCATRQEPLLIGSTKSNMGHPEPASGLAALAKVLLSLEHGLWAPNLHFHSPNPEIPALLDGRLQVVDQPLPVRGGNVGINSFGFGGSNVHIILRPNTQPPPAPAPHATLPRLLRASGRTPEAVQKLLEQGLRHSQDLAFLSMLNDIAAVPATAMPFRGYAVLGGERGGPEVQQVPAGERPLWFICSGMGTQWRGMGLSLMRLDRFRDSILRSDEAVKPFGLKVSQLLLSTDESTFDDIVHSFVSLTAIQIGLIDLLSCMGLRPDGIVGHSLGEVACGYADGCLSQEEAVLAAYWRGQCIKEAHLPPGAMAAVGLSWEECKQRCPPGVVPACHNSKDTVTISGPQAPVFEFVEQLRKEGVFAKEVRTGGMAFHSYFMEAIAPPLLQELKKVIREPKPRSARWLSTSIPEAQWHSSLARTSSAEYNVNNLVSPVLFQEALWHVPEHAVVLEIAPHALLQAVLKRGLKPSCTIIPLMKKDHRDNLEFFLAGIGRLHLSGIDANPNALFPPVEFPAPRGTPLISPLIKWDHSLAWDVPAAEDFPNGSGSPSAAIYNIDTSSESPDHYLVDHTLDGRVLFPATGYLSIVWKTLARALGLGVEQLPVVFEDVVLHQATILPKTGTVSLEVRLLEASRAFEVSENGNLVVSGKVYQWDDPDPRLFDHPESPTPNPTEPLFLAQAEVYKELRLRGYDYGPHFQGILEASLEGDSGRLLWKDNWVSFMDTMLQMSILGSAKHGLYLPTRVTAIHIDPATHRQKLYTLQDKAQVADVVVSRWLRVTVAGGVHISGLHTESAPRRQQEQQVPILEKFCFTPHTEEGCLSERAALQEELQLCKGLVQALQTKVTQQGLKMVVPGLDGAQIPRDPSQQELPRLLSAACRLQLNGNLQLELAQVLAQERPKLPEDPLLSGLLDSPALKACLDTAVENMPSLKMKVVEVLAGHGHLYSRIPGLLSPHPLLQLSYTATDRHPQALEAAQAELQQHDVAQGQWDPADPAPSALGSADLLVCNCAVAALGDPASALSNMVAALREGGFLLLHTLLRGHPLGDIVAFLTSTEPQYGQGILSQDAWESLFSRVSLRLVGLKKSFYGSTLFLCRRPTPQDSPIFLPVDDTSFRWVESLKGILADEDSSRPVWLKAINCATSGVVGLVNCLRREPGGNRLRCVLLSNLSSTSHVPEVDPGSAELQKVLQGDLVMNVYRDGAWGAFRHFLLEEDKPEEPTAHAFVSTLTRGDLSSIRWVCSSLRHAQPTCPGAQLCTVYYASLNFRDIMLATGKLSPDAIPGKWTSQDSLLGMEFSGRDASGKRVMGLVPAKGLATSVLLSPDFLWDVPSNWTLEEAASVPVVYSTAYYALVVRGRVRPGETLLIHSGSGGVGQAAIAIALSLGCRVFTTVGSAEKRAYLQARFPQLDSTSFANSRDTSFEQHVLWHTGGKGVDLVLNSLAEEKLQASVRCLATHGRFLEIGKFDLSQNHPLGMAIFLKNVTFHGVLLDAFFNESSADWREVWALVQAGIRDGVVRPLKCTVFHGAQVEDAFRYMAQGKHIGKVVVQVLAEEPEAVLKGAKPKLMSAISKTFCPAHKSYIIAGGLGGFGLELAQWLIQRGVQKLVLTSRSGIRTGYQAKQVRRWRRQGVQVQVSTSNISSLEGARGLIAEAAQLGPVGGVFNLAVVLRDGLLENQTPEFFQDVCKPKYSGTLNLDRVTREACPELDYFVVFSSVSCGRGNAGQSNYGFANSAMERICEKRRHEGLPGLAVQWGAIGDVGILVETMSTNDTIVSGTLPQRMASCLEVLDLFLNQPHMVLSSFVLAEKAAAYRDRDSQRDLVEAVAHILGIRDLAAVNLDSSLADLGLDSLMSVEVRQTLERELNLVLSVREVRQLTLRKLQELSSKADEASELACPTPKEDGLAQQQTQLNLRSLLVNPEGPTLMRLNSVQSSERPLFLVHPIEGSTTVFHSLASRLSIPTYGLQCTRAAPLDSIHSLAAYYIDCIRQVQPEGPYRVAGYSYGACVAFEMCSQLQAQQSPAPTHNSLFLFDGSPTYVLAYTQSYRAKLTPGCEAEAETEAICFFVQQFTDMEHNRVLEALLPLKGLEERVAAAVDLIIKSHQGLDRQELSFAARSFYYKLRAAEQYTPKAKYHGNVMLLRAKTGGAYGEDLGADYNLSQVCDGKVSVHVIEGDHRTLLEGSGLESIISIIHSSLAEPRVSVREG
Pos 1698 does not match wildtype amino acid K, V
Mutation K1699A does not match wildtype amino acid K at position 1698
Sequence: MEEVVIAGMSGKLPESENLQEFWDNLIGGVDMVTDDDRRWKAGLYGLPRRSGKLKDLSRFDASFFGVHPKQAHTMDPQLRLLLEVTYEAIVDGGINPDSLRGTHTGVWVGVSGSETSEALSRDPETLVGYSMVGCQRAMMANRLSFFFDFRGPSIALDTACSSSLMALQNAYQAIHSGQCPAAIVGGINVLLKPNTSVQFLRLGMLSPEGTCKAFDTAGNGYCRSEGVVAVLLTKKSLARRVYATILNAGTNTDGFKEQGVTFPSGDIQEQLIRSLYQSAGVAPESFEYIEAHGTGTKVGDPQELNGITRALCATRQEPLLIGSTKSNMGHPEPASGLAALAKVLLSLEHGLWAPNLHFHSPNPEIPALLDGRLQVVDQPLPVRGGNVGINSFGFGGSNVHIILRPNTQPPPAPAPHATLPRLLRASGRTPEAVQKLLEQGLRHSQDLAFLSMLNDIAAVPATAMPFRGYAVLGGERGGPEVQQVPAGERPLWFICSGMGTQWRGMGLSLMRLDRFRDSILRSDEAVKPFGLKVSQLLLSTDESTFDDIVHSFVSLTAIQIGLIDLLSCMGLRPDGIVGHSLGEVACGYADGCLSQEEAVLAAYWRGQCIKEAHLPPGAMAAVGLSWEECKQRCPPGVVPACHNSKDTVTISGPQAPVFEFVEQLRKEGVFAKEVRTGGMAFHSYFMEAIAPPLLQELKKVIREPKPRSARWLSTSIPEAQWHSSLARTSSAEYNVNNLVSPVLFQEALWHVPEHAVVLEIAPHALLQAVLKRGLKPSCTIIPLMKKDHRDNLEFFLAGIGRLHLSGIDANPNALFPPVEFPAPRGTPLISPLIKWDHSLAWDVPAAEDFPNGSGSPSAAIYNIDTSSESPDHYLVDHTLDGRVLFPATGYLSIVWKTLARALGLGVEQLPVVFEDVVLHQATILPKTGTVSLEVRLLEASRAFEVSENGNLVVSGKVYQWDDPDPRLFDHPESPTPNPTEPLFLAQAEVYKELRLRGYDYGPHFQGILEASLEGDSGRLLWKDNWVSFMDTMLQMSILGSAKHGLYLPTRVTAIHIDPATHRQKLYTLQDKAQVADVVVSRWLRVTVAGGVHISGLHTESAPRRQQEQQVPILEKFCFTPHTEEGCLSERAALQEELQLCKGLVQALQTKVTQQGLKMVVPGLDGAQIPRDPSQQELPRLLSAACRLQLNGNLQLELAQVLAQERPKLPEDPLLSGLLDSPALKACLDTAVENMPSLKMKVVEVLAGHGHLYSRIPGLLSPHPLLQLSYTATDRHPQALEAAQAELQQHDVAQGQWDPADPAPSALGSADLLVCNCAVAALGDPASALSNMVAALREGGFLLLHTLLRGHPLGDIVAFLTSTEPQYGQGILSQDAWESLFSRVSLRLVGLKKSFYGSTLFLCRRPTPQDSPIFLPVDDTSFRWVESLKGILADEDSSRPVWLKAINCATSGVVGLVNCLRREPGGNRLRCVLLSNLSSTSHVPEVDPGSAELQKVLQGDLVMNVYRDGAWGAFRHFLLEEDKPEEPTAHAFVSTLTRGDLSSIRWVCSSLRHAQPTCPGAQLCTVYYASLNFRDIMLATGKLSPDAIPGKWTSQDSLLGMEFSGRDASGKRVMGLVPAKGLATSVLLSPDFLWDVPSNWTLEEAASVPVVYSTAYYALVVRGRVRPGETLLIHSGSGGVGQAAIAIALSLGCRVFTTVGSAEKRAYLQARFPQLDSTSFANSRDTSFEQHVLWHTGGKGVDLVLNSLAEEKLQASVRCLATHGRFLEIGKFDLSQNHPLGMAIFLKNVTFHGVLLDAFFNESSADWREVWALVQAGIRDGVVRPLKCTVFHGAQVEDAFRYMAQGKHIGKVVVQVLAEEPEAVLKGAKPKLMSAISKTFCPAHKSYIIAGGLGGFGLELAQWLIQRGVQKLVLTSRSGIRTGYQAKQVRRWRRQGVQVQVSTSNISSLEGARGLIAEAAQLGPVGGVFNLAVVLRDGLLENQTPEFFQDVCKPKYSGTLNLDRVTREACPELDYFVVFSSVSCGRGNAGQSNYGFANSAMERICEKRRHEGLPGLAVQWGAIGDVGILVETMSTNDTIVSGTLPQRMASCLEVLDLFLNQPHMVLSSFVLAEKAAAYRDRDSQRDLVEAVAHILGIRDLAAVNLDSSLADLGLDSLMSVEVRQTLERELNLVLSVREVRQLTLRKLQELSSKADEASELACPTPKEDGLAQQQTQLNLRSLLVNPEGPTLMRLNSVQSSERPLFLVHPIEGSTTVFHSLASRLSIPTYGLQCTRAAPLDSIHSLAAYYIDCIRQVQPEGPYRVAGYSYGACVAFEMCSQLQAQQSPAPTHNSLFLFDGSPTYVLAYTQSYRAKLTPGCEAEAETEAICFFVQQFTDMEHNRVLEALLPLKGLEERVAAAVDLIIKSHQGLDRQELSFAARSFYYKLRAAEQYTPKAKYHGNVMLLRAKTGGAYGEDLGADYNLSQVCDGKVSVHVIEGDHRTLLEGSGLESIISIIHSSLAEPRVSVREG
Pos 1698 does not match wildtype amino acid K, V
Mutation K1699Q does not match wildtype amino acid K at position 1698

In [32]:
df['sequence'] = sequences

In [ ]:
print('Sequence with unmatched mutation information: ', len(df[df['sequence'].isna()]))
df = df.dropna(subset=['sequence'])
print('df length: ', len(df))

Sequence 정보가 틀린 데이터 수:  1636
df 길이:  18605

In [34]:
df.columns

Index(['Enzyme Variant', 'ec_number', 'uniprot', 'organism', 'temperature',
       'pH', 'parameter.name', 'parameter.type', 'parameter.associatedSpecies',
       'parameter.startValue', 'parameter.endValue',
       'parameter.standardDeviation', 'parameter.unit', 'substrate',
       'sequence', 'type', 'mutation', 'turnover_number', 'isomeric_smiles',
       'canonical_smiles'],
      dtype='object')

In [35]:
df.to_csv('data/sabiork_sequence_substrate.csv', index=False)